### ISSUE TITLE
Update Kubernetes admission docs with namespace selector to exclude OPA itself

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1215]
The current Kubernetes Admission control tutorial has the webhook configuration set to forward CREATE and UPDATE requests of all kinds in all namespaces to OPA. This creates a loop where OPA could make admission decisions for itself. We should update the webhook configuration in the tutorial to exclude the namespace that OPA is deployed into from admission checks.

**Comment by pandyamarut** [comment]
@tsandall Can you be more precise ? 
Thanks.

**Comment by phenixblue** [comment]
Would you want this to be an exclusion for the OPA namespace or an inclusion for target namespaces?

**Exclusion of OPA Namespace:**

Add `matchExpression` to VWC + label to OPA namespace

```yaml
namespaceSelector:
    matchExpressions:
    - key: openpolicyagent.org/admission-control
      operator: NotIn
      values:
      - disabled
```

**Inclusion for Target Namespaces:**

Add `namespaceSelector` to VWC + label on each target namespace

```yaml
namespaceSelector:
      matchLabels:
        openpolicyagent.org/admission-control: "enabled"
```
