### ISSUE TITLE
Cannot find bundle after download

### ISSUE THREAD

**Issue by quangtkfossil** [open-policy-agent/opa#1306]
I tried to read many times your document to understand how to configure. But when I tried to put the path of the bundle to Rego then got an error.

```
INFO[0000] Bundle downloaded and activated successfully. Etag updated to "5ca30fa1-387".  name=http/example/profile/bundle.tar.gz plugin=bundle
{"error":"1 error occurred: 1 error occurred: 1:1: rego_parse_error: no match found\n\t/http/example/profile\n\t^","go_version":"go1.12.1","level":"error","msg":""}
```

My config file:
```
services:
    name: server-opa
    url: http://localhost
    credentials:
        bearer:
          token: "xxx"

  bundle:
    name: http/example/profile/bundle.tar.gz
    service: server-opa
    prefix: bundles
    polling:
      min_delay_second: 10
      max_delay_second: 20

  default_decision: "/http/example/profile"
```

And then when I change the value of `default_decision` to use a dot: "http.example.profile".
Then I got an error:

```
INFO[0000] Bundle downloaded and activated successfully. Etag updated to "5ca30fa1-387".  name=http/example/profile/bundle.tar.gz plugin=bundle
{"error":"2 errors occurred:\n1:1: rego_unsafe_var_error: var http is unsafe\n1:1: rego_unsafe_var_error: var _ is unsafe","go_version":"go1.12.1","level":"error","msg":""}
```

**Comment by ashutosh-narkar** [comment]
You can run `opa run bundle.tar.gz` to debug your bundle and check if it is correctly structured. 

Can you paste the output of `tar tzf bundle.tar.gz`  and your policy ? 

Also `default_decision` should be `/http/example/profile` not `http.example.profile`.

**Comment by quangtkfossil** [comment]
@ashutosh-narkar : I run the opa command and it can read bundle but can't access the variable.

```
tkquang$ opa run bundle.tar.gz
OPA  (commit , built at )

Run 'help' to see a list of commands.

> permissions["normal"]
1 error occurred: 1:1: rego_unsafe_var_error: var permissions is unsafe
>
```

This is an output of untar bundle.
```
tkquang$ tar tzf bundle.tar.gz
http/
http/example/
http/example/.DS_Store
http/example/._.DS_Store
http/example/profile/
http/example/profile/profile.rego
http/.manifest
```

and my policy:
```
package rbac.authz

# HTTP API request
import input

errors["request denied by administrative policy"] {
  not allow
}

permissions = {
	"normal":		[{"method": "GET", "function": "GetProfile"}]
}

default allow = false

# Check by function
allow {
	r = input.role[_]
	pers = permissions[r]
	p = pers[_]
	{"method": input.method, "function": input.function} = p
}

```

**Comment by quangtkfossil** [comment]
Can anyone help me, pls?

**Comment by tsandall** [comment]
@quangtkfossil you're seeing the "var permission is unsafe" in the REPL because you're inside the wrong package. If you run `package rbac.authz` inside the REPL and then run `permissions` it'll work. Alternatively you can run `data.rbac.authz.permissions` from the default package in the REPL and see the same value.

As far as your original comment goes, I'm a bit lost:

1. Please post more logs. I don't know where the second line coming from. What is generating this?

```
{"error":"1 error occurred: 1 error occurred: 1:1: rego_parse_error: no match found\n\t/http/example/profile\n\t^","go_version":"go1.12.1","level":"error","msg":""}
```

2. The configuration file you provided is not valid, OPA will reject it. Please post the original configuration file that you're starting OPA with.

**Comment by quangtkfossil** [comment]
Hi @tsandall : Thank for your response. Now I understand about the unsafe error. 
And about the error `no match found`, I have printed in OPA parser and saw the log panic from: `opa/ast/parser.go`.
```
INFO[0000] Bundle downloaded and activated successfully. Etag updated to "5ca6c55a-38c".  name=http/example/profile/bundle.tar.gz plugin=bundle
1:1 (0): no match found, expected: "#", "(", "-", ".", "0", "[", "\"", "`", "default", "false", "import", "not", "null", "package", "set(", "true", "{", [ \t\r\n], [ \t], [1-9], [A-Za-z_] or EOF
{"error":"1 error occurred: 1 error occurred: 1:1: rego_parse_error: no match found\n\t/http/example/profile\n\t^","go_version":"go1.12.1","level":"error","msg":""}
```

With config I used:
```
services:
    name: server-opa
    url: http://localhost
    credentials:
        bearer:
          token: "xxx"

bundle:
    name: http/example/profile/bundle.tar.gz
    service: server-opa
    prefix: bundles
    polling:
      min_delay_second: 10
      max_delay_second: 20

default_decision: "/http/example/profile"
```
How do we fix it?

**Comment by tsandall** [comment]
@quangtkfossil the config you posted does not parse:

```
$ opa run -c ~/x.yaml 
error: config error: json: cannot unmarshal string into Go value of type rest.Config
$ cat ~/x.yaml
services:
    name: server-opa
    url: http://localhost
    credentials:
        bearer:
          token: "xxx"

bundle:
    name: http/example/profile/bundle.tar.gz
    service: server-opa
    prefix: bundles
    polling:
      min_delay_second: 10
      max_delay_second: 20

default_decision: "/http/example/profile"
```

You can fix it by nesting the service properly:

```
services:
    server-opa:
      url: http://localhost
      credentials:
        bearer:
          token: "xxx"

bundle:
    name: http/example/profile/bundle.tar.gz
    service: server-opa
    prefix: bundles
    polling:
      min_delay_second: 10
      max_delay_second: 20

default_decision: "/http/example/profile"
```
