### ISSUE TITLE
Add support for custom bundle deserializers/validators

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/opa#1416]
In some cases users need to apply custom deserialization or validation logic to bundles. We should give users the ability to hook in their own bundle deserializer/validator so that when bundles are read from disk/network, they can be processed by custom code (in the same way we support custom decision logger backends). For example:

```yaml
bundle:
  name: foo/bar
  plugin: custom_bundle_validator
plugins:
  custom_bundle_validator:
    param1: valuex
```

In Go, we can define a simple interface that the downloader package accepts that would override the default implementation:

```
type Deserializer interface {
  Read(r io.Reader) (*bundlle.Bundle, error)
}
```

The default implementation would just call the `bundle.Read` function.
