### ISSUE TITLE
Download bundles from OCI-compatible registries

### ISSUE THREAD

**Issue by omerlh** [open-policy-agent/opa#1464]
# Expected Behavior
OCI-compatible registries can be used to store anything, including OPA bundles (see [here](https://github.com/instrumenta/conftest#configuration-and-external-policies) a live example). I want to configure OPA with registry details and let it pull all the policy bundles from it (or specific bundles) 

# Actual Behavior
Bundle API supported, we can write a facade that translates Bundle API to OCI.

See also #1413 (thanks to @garethr!)

**Comment by garethr** [comment]
Some context to the use of OCI registries for storing artefacts other than Docker images here: https://stevelasker.blog/2019/01/25/cloud-native-artifact-stores-evolve-from-container-registries/

Conftest supports pushing and pulling OPA bundles, but I'd be happy to pull that out of Conftest and into OPA (or a standalone library) if folks thing this is useful elsewhere too.

The discussion in #1413 is intended to match up the mimetype/layers in the OCI image with the current bundle format described in the [docs](https://www.openpolicyagent.org/docs/latest/bundles#bundle-file-format).

The OPA config for using OCI bundles could be something like the following:

```yaml
services:
  - name: acr
     url: https://instrumenta.azurecr.io
     type: oci

bundle:
  name: kubernetes
  tag: latest
  service: acr
  name: kubernetes
  tag: latest
  service: acr
```

The assumption at the moment appears to be that aggregation of policies happens before creating the bundle, so only one bundle is downloaded. That likely makes directly reusable bundles harder to accomplish. The docs The docs cover how to configure bundle `.manifest` files to [deal with importing multiple bundles](https://www.openpolicyagent.org/docs/latest/bundles#multiple-sources-of-policy-and-data) but don't discuss how to then configure OPA to use multiple bundles.
