### ISSUE TITLE
Implement full ext_authz contract to support sending status code, response headers, and response body

### ISSUE THREAD

**Issue by ashutosh-narkar** [open-policy-agent/opa#1508]
The envoy ext_authz interface contains additional types that can convey additional information for the eventual Http Response, such as http status code, headers, and body.

The ext_authz Opa plugin could add some additional parameters for which aspects of the opa response to wire up to various different parts, e.g. something like

```
plugins:
     envoy.ext_authz.grpc:
       addr: :9191
       query: data.envoy.authz # This would essentially be the package being queried that contains the e.g. allow rule among other rules
       result: allow # This would be e.g. data.envoy.authz.allow, and would be used to determine OkHttpResponse vs DeniedHttpResponse as is being done today
       headers: response_headers # This could be a dict in the response payload that specifies key-value pairs for response headers
       body: response_body # This could be a simple string with a message sent back to the user for context
```

For more information see https://github.com/open-policy-agent/opa-istio-plugin/issues/87
