### ISSUE TITLE
Kubernetes admission controller passes policy evaluation if policy evaluation crashes due to an error

### ISSUE THREAD

**Issue by ferhaty** [open-policy-agent/opa#1529]
# Expected Behavior

Admission controller returns an error and blocks resource creation.

# Actual Behavior

Admission controller passes policy evaluation and creates incompliant resources

# Steps to Reproduce the Problem

*Rego Policy*:

```
package kubernetes.admission

import data.kubernetes.namespaces

import input.request.object.metadata.annotations as annotations

operations = {"CREATE", "UPDATE"}

deny[msg] {
    input.request.kind.kind = "Ingress"
    operations[input.request.operation]
    missing_required_annotations[msg]
}

missing_required_annotations[msg] {
    annotations["alb.ingress.kubernetes.io/tags"] == ""
    msg = "Compliance check failed: ELB_009: All load balancers must be tagged as per the tagging policy"
}
```

*Kubernetes Manifest*:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: test-ingress
spec:
  rules:
    - host: foo-bar.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80
          - path: /echo/
            backend:
              serviceName: echo-server
              servicePort: 80

```

*OPA ConfigMap*

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-default-system-main
  namespace: opa
data:
  main: |
    package system

    import data.kubernetes.admission

    main = {
      "apiVersion": "admission.k8s.io/v1beta1",
      "kind": "AdmissionReview",
      "response": response,
    }

    default response = {"allowed": true}

    response = {
        "allowed": false,
        "status": {
            "reason": reason,
        },
    } {
        reason = concat(", ", admission.deny)
        reason != ""
    }
```
  1. Ensure OPA is installed and running within the Kubernetes cluster
  2. Upload the Rego policy `kubectl create configmap lb-tag-check --from-file=lb-tag-check.rego`
  3. Apply the manifest using `kubectl apply -f ingress.yaml`

You can also reproduce it locally using `opa run`

1. Execute `opa run`
2. Enter `annotations := {"kubernetes.io/ingress.class": "alb", "alb.ingress.kubernetes.io/scheme": "internet-facing", "alb.ingress.kubernetes.io/target-type": "ip"}`
3. Enter ```missing_required_annotations[msg] {
    annotations["alb.ingress.kubernetes.io/tags"] == ""
    msg = "Compliance check failed: ELB_009: All load balancers must be tagged as per the tagging policy"
}```

You should see: `1 error occurred: 2:5: rego_type_error: undefined ref: data.repl.annotations["alb.ingress.kubernetes.io/tags"]`

# Additional Info

Using `image: openpolicyagent/opa:0.10.5`
Using `image: openpolicyagent/kube-mgmt:0.6`

Is it possible to check for undefined keys in a dictionary using Rego?
