### ISSUE TITLE
[Question] Kubernetes opa rules on users groups

### ISSUE THREAD

**Issue by ltagliamonte-dd** [open-policy-agent/opa#1572]
I'm currently using DEX for authentication and a bounce of RBAC rules with RoleBinding in order to filter actions per user `groups`.

Using `policies` and `rolebindings` that have namespace scope doesn't scale anymore, especially because a new policy and a new rolebinding needs to be created every time a new namespace gets created.

I'd like to have just a couple of ClusterRoles and then additionally filter per groups using OPA.

I couldn't really find any good example on how to achieve this. Can you please advise?
I'm running `openpolicyagent/kube-mgmt:0.8`

**Comment by patrick-east** [comment]
Hi! Can you provide a little more context for the policy and what you would like to achieve with it?

From a high level, if I understand correctly, you would need to have a way to get that group information into OPA and the association of groups and ClusterRoles (assuming that you mean to no longer have specific CRB's for each namespace).  Once you have that data in OPA it should be pretty easy to write policies around it. More info on the use-case will help us to give more specific advice.

If you haven't already be sure to join the slack group and check out the "kubernetes-policy" channel. There are a ton of other folks there that would probably be able to help a bit more (they may not all be watching github issues). Feel free to ping me there too 😄

**Comment by ltagliamonte-dd** [comment]
Hello @patrick-east thank you for replying.
Basically this is what I'm trying to have:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: non-privileged-reader
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: non-privileged-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: non-privileged-reader
subjects:
- kind: Group
  name: Engineering
```
this RBAC should give read on all namespaces and pods to all people in `Engineering`.
Using OPA I want to restrict this to all namespaces and pod not belonging to `kube-system` namespace.
