### ISSUE TITLE
Support for multiple services with discovery

### ISSUE THREAD

**Issue by omerlh** [open-policy-agent/opa#1714]
# Expected Behavior
I want to be able to use both discovery and status features. I want to have 2 different services - one for bundles and one for status update requests.

# Actual Behavior
It is not possible to have more than one service when discovery is enabled - look like it is by design (see this [line](https://github.com/open-policy-agent/opa/blob/74f4be41bcf69470e92de869cc713f3d5e76cee6/plugins/discovery/config.go#L55))

# Steps to Reproduce the Problem

  1. Configure OPA with both discovery and status:
```
services:
  - name: service-registry
    url: http://localhost:5000/
  - name: status
    url: http://localhost:3000/
discovery:
  name: /discovery.tar.gz
  prefix: bundles
  decision: discovery.config
status:
  service: status
```
  2. Run opa with the config file - `opa run -s -c config.yaml`)
  3. See the following error:
```
error: config error: discovery requires exactly one service
```

# Additional Info
OPA version -  0.13.0
