### ISSUE TITLE
Can't access OPA logs/status API on Kubernetes 

### ISSUE THREAD

**Issue by manicole** [open-policy-agent/opa#1766]
I'm trying to access `/logs` and `/status` API on OPA, without success ; I get 

> 404 page not found

# Expected Behavior
OPA 0.14.0 container running & ready in Kubernetes cluster, the address
`https://<IP-of-OPA-service>:<port-of-OPA-service>/logs`
should display the logs and the address
`https://<IP-of-OPA-service>:<port-of-OPA-service>/status`
should display the statuses.

# Actual Behavior
OPA 0.14.0 container running & ready in Kubernetes cluster, a curl at the address
`https://<IP-of-OPA-service>:<port-of-OPA-service>/logs`
display
> 404 page not found

and so does a curl at the address
`https://<IP-of-OPA-service>:<port-of-OPA-service>/status`.

Same behavior is observed with OPA 0.13.5.

# Steps to Reproduce the Problem
  1. Install OPA in a K8s cluster folloing steps 2, 3, 4 of [OPA official 0.13.5 documentation](https://www.openpolicyagent.org/docs/v0.13.5/kubernetes-admission-control/).

OPA deployment for version 0.14.0 is

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: opa
  namespace: opa
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:0.14.0
          args:
            - "run"
            - "--server"
            - "--tls-cert-file=/certs/tls.crt"
            - "--tls-private-key-file=/certs/tls.key"
            - "--addr=0.0.0.0:443"
            - "--addr=http://127.0.0.1:8181"
            - "--log-level=debug"
          volumeMounts:
            - readOnly: true
              mountPath: /certs
              name: opa-server
        - name: kube-mgmt
          image: openpolicyagent/kube-mgmt:0.9
          args:
            - "--replicate-cluster=v1/namespaces"
            - "--replicate=extensions/v1beta1/ingresses"
      volumes:
        - name: opa-server
          secret:
            secretName: opa-server
```

and OPA service is

```yaml
kind: Service
apiVersion: v1
metadata:
  name: opa
  namespace: opa
spec:
  selector:
    app: opa
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
```

  2. OPA container being running & ready and clusterIP opa service being 10.233.1.46,

`curl -X POST -k -s https://10.233.1.46:443/logs`

`curl -X POST -k -s https://10.233.1.46:443/status`

Obtained result is 
> 404 page not found

# Additional Info
Kubernetes v1.14.3

If of any use,
`curl -k -s https:///10.233.1.46:443/v1/metrics`
and
`curl -k -s https://10.233.1.46:443/v1/data`
work fine.
