### ISSUE TITLE
Provide image suitable for CI run

### ISSUE THREAD

**Issue by grzesuav** [open-policy-agent/opa#1789]
I try to use `openpolicyagent/opa:0.14.0` in my gitlab-ci job: 
```yaml
test-rego-rules:
  image:
    name: openpolicyagent/opa:0.14.1
    entrypoint: ["/opa"]
  script:
  - test . -v
  stage: test
```
# Expected Behavior

I would expect that this image will be working in CI, executing command.

# Actual Behavior
output from runner :
```
[0Kunknown command "sh" for "opa"
Error: unknown command "sh" for "opa"
Run 'opa --help' for usage.
section_end:1569325132:build_script
[0Ksection_start:1569325132:after_script
[0Kunknown command "sh" for "opa"
```
it seems that (https://docs.gitlab.com/ee/ci/yaml/#script) commands are wrapped via `sh` (which makes sense in case of CI)

# Steps to Reproduce the Problem

  1. Create project on gitlab.com
  2. Use code snippet as gitlab-ci.yaml
  3. Commit and see pipeline results

# Additional Info
I am happy with other image variant (like `openpolicyagent/opa:0.14.1-alpine`) which would be suitable for CI
