### ISSUE TITLE
Add metrics for data item count

### ISSUE THREAD

**Issue by rtoma** [open-policy-agent/opa#1811]
We got bitten by the kube-mgmt 0.9 bug that caused moments of incomplete opa data.
Please instrument the opa code and expose metrics on the number of data items per package. 

In our case a count for `kubernetes.namespaces` items would have made us aware of the issue  earlier.

**Comment by tsandall** [comment]
@rtoma thanks for filing this.

It's going to be difficult to have a generic metrics for data item counts because you can load whatever you want into OPA. I could imagine exposing configuration that lets users pick which paths they want to monitor and making some recommendations for specific deployments (e.g., Kubernetes admission control).

For example in the OPA configuration:

```
monitoring:
  custom_metrics:
    k8s_namespaces:
      type: data_count_gauge
      path: /kubernetes/namespaces
```

On the command line:

```
opa run \
  --set monitoring.custom_metrics.k8s_namespaces.type=data_count_gauge \
  --set monitoring.custom_metrics.k8s_namespaces.path=/kubernetes/namespaces
```
