### ISSUE TITLE
OPA timing out installed via Helm

### ISSUE THREAD

**Issue by steve21168** [open-policy-agent/opa#1942]
# Expected Behavior
Helm chart to install successfully and use configmap with rules to validate API requests

# Actual Behavior
Helm chart installs successfully and requests to the API timeout attempting to use webhooks to OPA

# Steps to Reproduce the Problem

  1.  Install helm chart with given value overrides

# Additional Info
Platform: EKS
Kubernetes version: 1.14
Helm: stable/opa  1.12.0, Values below

Hi I’m having trouble installing OPA in my EKS cluster from the helm chart.  The chart installs, the mgmt container seems to annotate my rules from the configmap but requests to the API seem to timeout using OPA as the admission controller.  Get/Delete requests to the kube-api seem to work okay but it seems like all my create requests will timeout attempting to validate with OPA

Reviewing my logs
My Kubernetes API Logs show:

> failed calling webhook "webhook.openpolicyagent.org": Post https://opa.kube-system.svc:443/?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

The mgmt container shows:

> time="2019-12-04T17:07:23Z" level=error msg="Failed to openpolicyagent.org/policy-status for kube-system/image-policy: Timeout: request did not complete within requested timeout 30s"

The opa container only shows logs of the health checks which are all returning 200s

The config map image-policy is the one policy I’ve written and the annotation has been added:

>  annotations:
      openpolicyagent.org/policy-status: '{"status":"ok"}'

I’ve also tested my rego policy locally and it works as intended.

Values overrides:
```
admissionControllerRules:
  - operations: ["*"]
    apiGroups: ["*"]
    apiVersions: ["*"]
    resources: ["*"]

mgmt:
  enabled: true
  configmapPolicies:
    enabled: true
    namespaces: [kube-system]
    requireLabel: true

resources: {}

rbac:
  create: true
  rules:
    cluster:
    - apiGroups:
        - ""
      resources:
      - configmaps
      verbs:
      - get
      - list
      - watch
      - patch
      - update

serviceAccount:
  create: true
  name: opa
```

Thanks for your help!
