### ISSUE TITLE
config error: plugin "envoy.ext_authz.grpc" not registered

### ISSUE THREAD

**Issue by kadimulam** [open-policy-agent/opa#2179]
We are using Envoy RPM and configured "envoy.ext_authz" HTTP filter. Within config.yaml, we used below plugin for external authorization using OPA (we are using https://openpolicyagent.org/downloads/latest/opa_linux_amd64). Everything is configured inside a dockerfile.

```
plugins:
     envoy.ext_authz.grpc:
       addr: :9191
       query: data.envoy.authz.allow
```

When we try to run the Docker we are getting below error.
`error: config error: plugin "envoy.ext_authz.grpc" not registered`

Is envoy.ext_authz.grpc plugin available as part of OPA binary? As recommended here ( https://github.com/open-policy-agent/opa/issues/1509), we are trying to build the binary from source, but we encountered issues reported here https://github.com/open-policy-agent/opa/issues/2162

Do we have any fix for this issue?
