### ISSUE TITLE
OPA not applying mutating webhook to Deployment

### ISSUE THREAD

**Issue by nitishm** [open-policy-agent/opa#2325]
# Expected Behavior
Based on the mutating-webhook example from the repository, the mutation must occur on the tagged Deployment

*Deployment with annotation as the trigger* - nginx-deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: opa
  labels:
    app: nginx
  annotations:
    test-mutation: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

*Rego policy* - main.rego
```
package library.kubernetes.admission.mutating
###########################################################################
# Implementation of the k8s admission control external webhook interface,
# combining validating and mutating admission controllers
###########################################################################
main = {
	"apiVersion": "admission.k8s.io/v1beta1",
	"kind": "AdmissionReview",
	"response": response,
}
default response = {"allowed": true}
# non-patch response i.e. validation response
response = x {
	count(patch) == 0
	x := {
		"allowed": false,
		"status": {"reason": reason},
	}
	reason = concat(", ", deny)
	reason != ""
}
# patch response i.e. mutating respone
response = x {
	count(patch) > 0
	# if there are missing leaves e.g. trying to add a label to something that doesn't
	# yet have any, we need to create the leaf nodes as well
	fullPatches := ensureParentPathsExist(cast_array(patch))
	x := {
		"allowed": true,
		"patchType": "JSONPatch",
		"patch": base64.encode(json.marshal(fullPatches)),
	}
}
isValidRequest {
	# not sure if this might be a race condition, it might get called before
	# all the validation rules have been run
	count(deny) == 0
}
isCreateOrUpdate {
	isCreate
}
isCreateOrUpdate {
	isUpdate
}
isCreate {
	input.request.operation == "CREATE"
}
isUpdate {
	input.request.operation == "UPDATE"
}
###########################################################################
# PATCH helpers
# Note: These rules assume that the input is an object
# not an AdmissionRequest, because labels and annotations
# can apply to various sub-objects within a request
# So from the context of an AdmissionRequest they need to
# be called like
#   hasLabelValue("foo", "bar") with input as input.request.object
# or
#   hasLabelValue("foo", "bar") with input as input.request.oldObject
###########################################################################
hasLabels(obj) {
	obj.metadata.labels
}
hasLabel(obj, label) {
	obj.metadata.labels[label]
}
hasLabelValue(obj, key, val) {
	obj.metadata.labels[key] = val
}
hasAnnotations(obj) {
	obj.metadata.annotations
}
hasAnnotation(obj, annotation) {
	obj.metadata.annotations[annotation]
}
hasAnnotationValue(obj, key, val) {
	obj.metadata.annotations[key] = val
}
###########################################################################
# makeLabelPatch creates a label patch
# Labels can exist on numerous child objects e.g. Deployment.template.metadata
# Use pathPrefix to specify a lower level object, or pass "" to select the
# top level object
# Note: pathPrefix should have a leading '/' but no trailing '/'
###########################################################################
makeLabelPatch(op, key, value, pathPrefix) = patchCode {
	patchCode = {
		"op": op,
		"path": concat("/", [pathPrefix, "metadata/labels", replace(key, "/", "~1")]),
		"value": value,
	}
}
makeAnnotationPatch(op, key, value, pathPrefix) = patchCode {
	patchCode = {
		"op": op,
		"path": concat("/", [pathPrefix, "metadata/annotations", replace(key, "/", "~1")]),
		"value": value,
	}
}
# Given array of JSON patches create and prepend new patches that create missing paths.
ensureParentPathsExist(patches) = result {
	# Convert patches to a set
	paths := {p.path | p := patches[_]}
	# Compute all missing subpaths.
	#    Iterate over all paths and over all subpaths
	#    If subpath doesn't exist, add it to the set after making it a string
	missingPaths := {sprintf("/%s", [concat("/", prefixPath)]) |
		paths[path]
		pathArray := split(path, "/")
		pathArray[i] # walk over path
		i > 0 # skip initial element
		# array of all elements in path up to i
		prefixPath := [pathArray[j] | pathArray[j]; j < i; j > 0] # j > 0: skip initial element
		walkPath := [toWalkElement(x) | x := prefixPath[_]]
		not inputPathExists(walkPath) with input as input.request.object
	}
	# Sort paths, to ensure they apply in correct order
	ordered_paths := sort(missingPaths)
	# Return new patches prepended to original patches.
	#  Don't forget to prepend all paths with a /
	new_patches := [{"op": "add", "path": p, "value": {}} |
		p := ordered_paths[_]
	]
	result := array.concat(new_patches, patches)
}
# Check that the given @path exists as part of the input object.
inputPathExists(path) {
	walk(input, [path, _])
}
toWalkElement(str) = str {
	not re_match("^[0-9]+$", str)
}
toWalkElement(str) = x {
	re_match("^[0-9]+$", str)
	x := to_number(str)
}
############################################################
# PATCH rules 
#
# Note: All patch rules should start with `isValidRequest` and `isCreateOrUpdate`
############################################################
patch[patchCode] {
    isValidRequest
	isCreateOrUpdate
	input.request.kind == "Deployment"
	input.request.object.metadata.annotations["test-mutation"]
	patchCode = makeLabelPatch("add", "foo", "bar", "")
}
```

*Request and response from opa container logs*
```json
{
  "client_addr": "127.0.0.1:53742",
  "level": "info",
  "msg": "Received request.",
  "req_body": "package library.kubernetes.admission.mutating\n\n###########################################################################\n# Implementation of the k8s admission control external webhook interface,\n# combining validating and mutating admission controllers\n###########################################################################\n\nmain = {\n\t\"apiVersion\": \"admission.k8s.io/v1beta1\",\n\t\"kind\": \"AdmissionReview\",\n\t\"response\": response,\n}\n\ndefault response = {\"allowed\": true}\n\n# non-patch response i.e. validation response\nresponse = x {\n\tcount(patch) == 0\n\n\tx := {\n\t\t\"allowed\": false,\n\t\t\"status\": {\"reason\": reason},\n\t}\n\n\treason = concat(\", \", deny)\n\treason != \"\"\n}\n\n# patch response i.e. mutating respone\nresponse = x {\n\tcount(patch) > 0\n\n\t# if there are missing leaves e.g. trying to add a label to something that doesn't\n\t# yet have any, we need to create the leaf nodes as well\n\n\tfullPatches := ensureParentPathsExist(cast_array(patch))\n\n\tx := {\n\t\t\"allowed\": true,\n\t\t\"patchType\": \"JSONPatch\",\n\t\t\"patch\": base64.encode(json.marshal(fullPatches)),\n\t}\n}\n\nisValidRequest {\n\t# not sure if this might be a race condition, it might get called before\n\t# all the validation rules have been run\n\tcount(deny) == 0\n}\n\nisCreateOrUpdate {\n\tisCreate\n}\n\nisCreateOrUpdate {\n\tisUpdate\n}\n\nisCreate {\n\tinput.request.operation == \"CREATE\"\n}\n\nisUpdate {\n\tinput.request.operation == \"UPDATE\"\n}\n\n###########################################################################\n# PATCH helpers\n# Note: These rules assume that the input is an object\n# not an AdmissionRequest, because labels and annotations\n# can apply to various sub-objects within a request\n# So from the context of an AdmissionRequest they need to\n# be called like\n#   hasLabelValue(\"foo\", \"bar\") with input as input.request.object\n# or\n#   hasLabelValue(\"foo\", \"bar\") with input as input.request.oldObject\n###########################################################################\n\nhasLabels(obj) {\n\tobj.metadata.labels\n}\n\nhasLabel(obj, label) {\n\tobj.metadata.labels[label]\n}\n\nhasLabelValue(obj, key, val) {\n\tobj.metadata.labels[key] = val\n}\n\nhasAnnotations(obj) {\n\tobj.metadata.annotations\n}\n\nhasAnnotation(obj, annotation) {\n\tobj.metadata.annotations[annotation]\n}\n\nhasAnnotationValue(obj, key, val) {\n\tobj.metadata.annotations[key] = val\n}\n\n###########################################################################\n# makeLabelPatch creates a label patch\n# Labels can exist on numerous child objects e.g. Deployment.template.metadata\n# Use pathPrefix to specify a lower level object, or pass \"\" to select the\n# top level object\n# Note: pathPrefix should have a leading '/' but no trailing '/'\n###########################################################################\n\nmakeLabelPatch(op, key, value, pathPrefix) = patchCode {\n\tpatchCode = {\n\t\t\"op\": op,\n\t\t\"path\": concat(\"/\", [pathPrefix, \"metadata/labels\", replace(key, \"/\", \"~1\")]),\n\t\t\"value\": value,\n\t}\n}\n\nmakeAnnotationPatch(op, key, value, pathPrefix) = patchCode {\n\tpatchCode = {\n\t\t\"op\": op,\n\t\t\"path\": concat(\"/\", [pathPrefix, \"metadata/annotations\", replace(key, \"/\", \"~1\")]),\n\t\t\"value\": value,\n\t}\n}\n\n# Given array of JSON patches create and prepend new patches that create missing paths.\nensureParentPathsExist(patches) = result {\n\t# Convert patches to a set\n\tpaths := {p.path | p := patches[_]}\n\n\t# Compute all missing subpaths.\n\t#    Iterate over all paths and over all subpaths\n\t#    If subpath doesn't exist, add it to the set after making it a string\n\tmissingPaths := {sprintf(\"/%s\", [concat(\"/\", prefixPath)]) |\n\t\tpaths[path]\n\t\tpathArray := split(path, \"/\")\n\t\tpathArray[i] # walk over path\n\t\ti > 0 # skip initial element\n\n\t\t# array of all elements in path up to i\n\t\tprefixPath := [pathArray[j] | pathArray[j]; j < i; j > 0] # j > 0: skip initial element\n\t\twalkPath := [toWalkElement(x) | x := prefixPath[_]]\n\t\tnot inputPathExists(walkPath) with input as input.request.object\n\t}\n\n\t# Sort paths, to ensure they apply in correct order\n\tordered_paths := sort(missingPaths)\n\n\t# Return new patches prepended to original patches.\n\t#  Don't forget to prepend all paths with a /\n\tnew_patches := [{\"op\": \"add\", \"path\": p, \"value\": {}} |\n\t\tp := ordered_paths[_]\n\t]\n\n\tresult := array.concat(new_patches, patches)\n}\n\n# Check that the given @path exists as part of the input object.\ninputPathExists(path) {\n\twalk(input, [path, _])\n}\n\ntoWalkElement(str) = str {\n\tnot re_match(\"^[0-9]+$\", str)\n}\n\ntoWalkElement(str) = x {\n\tre_match(\"^[0-9]+$\", str)\n\tx := to_number(str)\n}\n\n############################################################\n# PATCH rules \n#\n# Note: All patch rules should start with `isValidRequest` and `isCreateOrUpdate`\n############################################################\n\npatch[patchCode] {\n    isValidRequest\n\tisCreateOrUpdate\n\tinput.request.kind == \"Deployment\"\n\tinput.request.object.metadata.annotations[\"test-mutation\"]\n\tpatchCode = makeLabelPatch(\"add\", \"foo\", \"bar\", \"\")\n}\n",
  "req_id": 22,
  "req_method": "PUT",
  "req_params": {},
  "req_path": "/v1/policies/opa/mutate/main.rego",
  "time": "2020-04-21T16:16:37Z"
}
{
  "client_addr": "127.0.0.1:53392",
  "level": "info",
  "msg": "Received request.",
  "req_body": "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{\"deployment.kubernetes.io/revision\":\"1\",\"test-mutation\":\"true\"},\"creationTimestamp\":\"2020-04-21T16:16:37Z\",\"generation\":1,\"labels\":{\"app\":\"nginx\"},\"managedFields\":[{\"apiVersion\":\"apps/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\"f:deployment.kubernetes.io/revision\":{}}},\"f:status\":{\"f:conditions\":{\".\":{},\"k:{\\\"type\\\":\\\"Available\\\"}\":{\".\":{},\"f:lastTransitionTime\":{},\"f:lastUpdateTime\":{},\"f:message\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"Progressing\\\"}\":{\".\":{},\"f:lastTransitionTime\":{},\"f:lastUpdateTime\":{},\"f:message\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}}},\"f:observedGeneration\":{},\"f:replicas\":{},\"f:unavailableReplicas\":{},\"f:updatedReplicas\":{}}},\"manager\":\"kube-controller-manager\",\"operation\":\"Update\",\"time\":\"2020-04-21T16:16:37Z\"},{\"apiVersion\":\"apps/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:test-mutation\":{}},\"f:labels\":{\".\":{},\"f:app\":{}}},\"f:spec\":{\"f:progressDeadlineSeconds\":{},\"f:replicas\":{},\"f:revisionHistoryLimit\":{},\"f:selector\":{\"f:matchLabels\":{\".\":{},\"f:app\":{}}},\"f:strategy\":{\"f:rollingUpdate\":{\".\":{},\"f:maxSurge\":{},\"f:maxUnavailable\":{}},\"f:type\":{}},\"f:template\":{\"f:metadata\":{\"f:labels\":{\".\":{},\"f:app\":{}}},\"f:spec\":{\"f:containers\":{\"k:{\\\"name\\\":\\\"nginx\\\"}\":{\".\":{},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:name\":{},\"f:ports\":{\".\":{},\"k:{\\\"containerPort\\\":80,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{},\"f:containerPort\":{},\"f:protocol\":{}}},\"f:resources\":{},\"f:terminationMessagePath\":{},\"f:terminationMessagePolicy\":{}}},\"f:dnsPolicy\":{},\"f:restartPolicy\":{},\"f:schedulerName\":{},\"f:securityContext\":{},\"f:terminationGracePeriodSeconds\":{}}}}},\"manager\":\"kubectl\",\"operation\":\"Update\",\"time\":\"2020-04-21T16:16:37Z\"}],\"name\":\"nginx-deployment\",\"namespace\":\"opa\",\"resourceVersion\":\"1124887\",\"selfLink\":\"/apis/apps/v1/namespaces/opa/deployments/nginx-deployment\",\"uid\":\"37979c75-ced3-4be4-b0cb-1260bcfaf278\"},\"spec\":{\"progressDeadlineSeconds\":600,\"replicas\":1,\"revisionHistoryLimit\":10,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"strategy\":{\"rollingUpdate\":{\"maxSurge\":\"25%\",\"maxUnavailable\":\"25%\"},\"type\":\"RollingUpdate\"},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.14.2\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80,\"protocol\":\"TCP\"}],\"resources\":{},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\"}],\"dnsPolicy\":\"ClusterFirst\",\"restartPolicy\":\"Always\",\"schedulerName\":\"default-scheduler\",\"securityContext\":{},\"terminationGracePeriodSeconds\":30}}},\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2020-04-21T16:16:37Z\",\"lastUpdateTime\":\"2020-04-21T16:16:37Z\",\"message\":\"Deployment does not have minimum availability.\",\"reason\":\"MinimumReplicasUnavailable\",\"status\":\"False\",\"type\":\"Available\"},{\"lastTransitionTime\":\"2020-04-21T16:16:37Z\",\"lastUpdateTime\":\"2020-04-21T16:16:37Z\",\"message\":\"ReplicaSet \\\"nginx-deployment-6b474476c4\\\" is progressing.\",\"reason\":\"ReplicaSetUpdated\",\"status\":\"True\",\"type\":\"Progressing\"}],\"observedGeneration\":1,\"replicas\":1,\"unavailableReplicas\":1,\"updatedReplicas\":1}}\n",
  "req_id": 23,
  "req_method": "PUT",
  "req_params": {},
  "req_path": "/v1/data/kubernetes/deployments/opa/nginx-deployment",
  "time": "2020-04-21T16:16:37Z"
}
```
# Actual Behavior
No mutations occur on the deployment object. Response code 204 with no response body

# Steps to Reproduce the Problem

  1. Deploy OPA
  2. Create configmap from file main.rego (contents shown above)
  3. Deploy nginx-deployment.yaml (contents shown above)

# Additional Info
OPA deployment steps from https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/. Applied validation steps to create mutating webhook
```yaml
# Grant OPA/kube-mgmt read-only access to resources. This lets kube-mgmt
# replicate resources into OPA so they can be used in policies.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opa-viewer
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:opa
  apiGroup: rbac.authorization.k8s.io
---
# Define role for OPA/kube-mgmt to update configmaps with policy status.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: opa
  name: configmap-modifier
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "patch"]
---
# Grant OPA/kube-mgmt role defined above.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: opa
  name: opa-configmap-modifier
roleRef:
  kind: Role
  name: configmap-modifier
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:opa
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: opa
  namespace: opa
spec:
  selector:
    app: opa
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opa
  namespace: opa
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      containers:
        # WARNING: OPA is NOT running with an authorization policy configured. This
        # means that clients can read and write policies in OPA. If you are
        # deploying OPA in an insecure environment, be sure to configure
        # authentication and authorization on the daemon. See the Security page for
        # details: https://www.openpolicyagent.org/docs/security.html.
        - name: opa
          image: openpolicyagent/opa:0.11.0
          args:
            - "run"
            - "--server"
            - "--tls-cert-file=/certs/tls.crt"
            - "--tls-private-key-file=/certs/tls.key"
            - "--addr=0.0.0.0:443"
            - "--addr=http://127.0.0.1:8181"
          volumeMounts:
            - readOnly: true
              mountPath: /certs
              name: opa-server
        - name: kube-mgmt
          image: openpolicyagent/kube-mgmt:0.8
          args:
            - "--replicate-cluster=v1/namespaces"
            - "--replicate=extensions/v1beta1/ingresses"
            - "--replicate=apps/v1/deployments"
      volumes:
        - name: opa-server
          secret:
            secretName: opa-server
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-default-system-main
  namespace: opa
data:
  main: |
    package system
    import data.kubernetes.admission
    main = {
      "apiVersion": "admission.k8s.io/v1beta1",
      "kind": "AdmissionReview",
      "response": response,
    }
    default response = {"allowed": true}
    response = {
        "allowed": false,
        "status": {
            "reason": reason,
        },
    } {
        reason = concat(", ", admission.deny)
        reason != ""
    }
```
CC: @sanskriti-s

**Comment by patrick-east** [comment]
I think there are maybe a couple things to check on.

If the yaml you specified is how OPA was deployed, in particular the `args` for the `opa` container and the `ConfigMap` defining `data.system.main` then the result you are seeing makes sense.

The `main.rego` mutation policy you defined specifies:
```rego
package library.kubernetes.admission.mutating
```
so the fully qualified path to its `main` is `data.library.kubernetes.admission.mutating.main`, which will yield the admission response with the patches.

As-is, if the yaml above for OPA's deployment is what you've got deployed, that path wont be evaluated.

By default when using the `/` query path OPA will evaluate `data.system.main` (see https://www.openpolicyagent.org/docs/latest/rest-api/#query-api ) which is defined in that little snippet of rego for the example admission controller  in 
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-default-system-main
  namespace: opa
data:
  main: |
    package system
    import data.kubernetes.admission
    main = {
      "apiVersion": "admission.k8s.io/v1beta1",
      "kind": "AdmissionReview",
      "response": response,
    }
    default response = {"allowed": true}
    response = {
        "allowed": false,
        "status": {
            "reason": reason,
        },
    } {
        reason = concat(", ", admission.deny)
        reason != ""
    }
```

So you have a couple of options to connect things. You can change the OPA arguments to specify a new `default_decision` https://www.openpolicyagent.org/docs/latest/configuration/#miscellaneous like `--set default_decision=data.library.kubernetes.admission.mutating.main` or change the `data.system.main` policy to reference the mutation one like:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-default-system-main
  namespace: opa
data:
  main: |
    package system
    import data.library.kubernetes.admission.mutating
    
    main = mutating.main
```
The idea is that you need OPA to be evaluating the mutation policies and returning the payload defined there.
