### ISSUE TITLE
open policy agent - OPA - How to use --config-file from kubernetes configmap object

### ISSUE THREAD

**Issue by ajoysinhactc** [open-policy-agent/opa#2363]
**_This is a query rather than an issue_**
 

1. OPA installed as a sidecar in Kubernetes
2. Policy will be managed as bundle
3. OPA policy will be stored and served from a separate service [ Bundle ]
4. OPA need to be configured using config-file to get the policy from external service
5. config-file will be stored as a config map in kubernetes.
6. That config map need to be used in --config-file

My config map in kubernetes

```
kubectl create configmap policyconfig --from-file=./config/config.yaml
```

My Sidecar OPA

```
- name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:443"
            - "--addr=0.0.0.0:8181"
            - "--config-file=policyconfig"
      volumes:
        - name: policyconfig
          configMap:
            name: policyconfig
```
Getting an error as below during pod creation

```
error: config error: open policyconfig: no such file or directory
```

is it possible to implement in this way

**Comment by ajoysinhactc** [comment]
I have found the answer and it is as below 
```
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:443"
            - "--addr=0.0.0.0:8181"
            - "--config-file=/config/config.yaml"
          volumeMounts:
            - readOnly: true
              mountPath: /config
              name: policyconfig
      volumes:
        - name: policyconfig
          configMap:
            name: policyconfig
```
