### ISSUE TITLE
ertificate is not valid for any names, but wanted to match admission-controller.opa-istio.svc

### ISSUE THREAD

**Issue by ajoysinha** [open-policy-agent/opa#2477]
This is a question.

I am planning to change default "TLS certificate for OPA admission controller". and followed following steps.

1. Created openssl sertificate using following command [ I have passed all other info blank ]
```
openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out AjoyCertificate.crt -keyout AjoyKey.key

```
2. got the tls.crt from AjoyCertificate.crt and use at server-cert secret
3. got tls.key from AjoyKey.key and use at server-cert secret
4. deploy iostio-opa

Now when I am deploying the application in cluster [ minikube ] applications are not deployed, it is getting following error 
```
Internal error occurred: failed calling webhook "istio.openpolicyagent.org": Post https://admission-controller.opa-istio.svc:443/v0/data/istio/inject?timeout=30s: x509: certificate is not valid for any names, but wanted to match admission-controller.opa-istio.svc
```

Not sure how to resolve this issue : "certificate is not valid for any names"

**Comment by ajoysinha** [comment]
I have tried to create the certificate with domain name "admission-controller.opa-istio.svc"

Now I am getting following error

```
Internal error occurred: failed calling webhook "istio.openpolicyagent.org": Post https://admission-controller.opa-istio.svc:443/v0/data/istio/inject?timeout=30s: x509: certificate signed by unknown authority
```

**Comment by ajoysinha** [comment]
Here is my kube.config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/ajoy/.minikube/ca.crt
    server: https://192.168.39.44:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/ajoy/.minikube/profiles/minikube/client.crt
    client-key: /home/ajoy/.minikube/profiles/minikube/client.key
```
