### ISSUE TITLE
OPA data in config map is not working as expected

### ISSUE THREAD

**Issue by ajoysinha** [open-policy-agent/opa#2488]
I am trying to pass **policy and data** both through config map. policy is working fine ..but data is not working .. my implementation is as below.

Data :
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-data
  namespace: default
  labels:
    openpolicyagent.org/data: opa
data:
  data.json: |
     {"customer": { "001": {"familyhead": "YES" }, "002": { "familyhead": "NO" }, "003": { "familyhead": "NO" }, "004": { "familyhead": "YES" }, "005": { "familyhead": "NO" } } }
    
```

Data loading 

```
"args": [
        "run",
        "--server",
        .........
        "/policy/policy.rego"
        "/data/data.json"
      ],
      ....
"volumeMounts": [ 
      .....
      {
        "mountPath": "/policy",
        "name": "opa-policy",
      }, {
        "mountPath": "/data",
        "name": "opa-data",
      }]
.....
opa_policy_volume = {
      "name": "opa-policy",
      "configMap": {"name": "opa-policy"},
    }
    opa_data_volume = {
      "name": "opa-data",
      "configMap": {"name": "opa-data"},
    }

```

My Policy implementation. 

```
    allow = true {
      customer_is_familyhead
    }

    customer_is_familyhead {
      data.opa["opa-data"]["data.json"].customer[useridfromtoken].familyhead = "YES"
    }
    
```
It seems to me that "customer_is_familyhead" is not working.
