### ISSUE TITLE
Support AWS Web Identities

### ISSUE THREAD

**Issue by danielmoore** [open-policy-agent/opa#2607]
I'm running OPA in EKS using [service account IAM roles](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html) to grant access to S3. This adds the following env vars:

```
AWS_ROLE_ARN=arn:aws:iam::{my account}:role/{my role}
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

## Expected Behavior

I would like to configure OPA as:

```yml
services:
  s3:
    url: https://mybucket.s3.us-east-1.amazonaws.com/
    credentials:
      s3_signing:
        environment_credentials:
          AWS_ROLE_ARN: $AWS_ROLE_ARN
          AWS_WEB_IDENTITY_TOKEN_FILE: $AWS_WEB_IDENTITY_TOKEN_FILE
```

## Actual Behavior

I get this in the logs:

```
{"level":"error","msg":"Bundle download failed: request failed: error getting AWS credentials: no AWS_ACCESS_KEY_ID set in environment","name":"http","plugin":"bundle","time":"2020-08-04T23:14:19Z"}
```

## Steps to Reproduce the Problem

1. Deploy an EKS cluster with OIDC enabled
2. Deploy OPA with a service account mapped to an IAM role

## Additional Info

- This seems related to #1600 and #2342 
- [AWS Web Identity docs for AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-oidc)
- [AWS Go SDK Web Identity provider](https://github.com/aws/aws-sdk-go/blob/f6443cd3144c36f0470a6b2230f1c315979d01de/aws/credentials/stscreds/web_identity_provider.go)
