### ISSUE TITLE
Policy not getting enforced when Enabling both webhooks

### ISSUE THREAD

**Issue by AnjaliRajan24** [open-policy-agent/opa#2660]
Hi, I have installed OPA using helm. I am following along https://github.com/open-policy-agent/library/tree/master/kubernetes/mutating-admission tutorial but even though my validation policy is annotated as status ok, it is not getting enforced and mutation policy is unable to call func defined in main.

## Expected Behavior
Admission control policy to be enforced and block images not being pulled from the specific registry

## Actual Behavior
Admission control policy not enforced and allowing deployments even if images not being pulled from the specific registry.

## Steps to Reproduce the Problem
Main cm- https://gist.github.com/AnjaliRajan24/e99bd276cd1ee480eb59831899677c11
mutation policy- https://gist.github.com/AnjaliRajan24/5b38bccd2fb5e3d5134d8d1449f2460e
Validation policy- https://gist.github.com/AnjaliRajan24/f965b5eabfc23725795c2907b48e1790

Error with mutation policy- 
```
"openpolicyagent.org/policy-status": "{\"status\":\"error\",\"error\":{\"code\":\"invalid_parameter\",\"message\":\"error(s) occurred while compiling module(s)\",\"errors\":[{\"code\":\"rego_unsafe_var_error\",\"message\":\"var isCreateOrUpdate is unsafe\",\"location\":{\"file\":\"opa/foo-policy/admission-policy\",\"row\":3,\"col\":3}}]}}"
```

Error with validation policy-
` "openpolicyagent.org/policy-status": "{\"status\":\"ok\"}"`

 ```
kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml -n norbert
deployment.apps/nginx-deployment created
```

kube-mgmt log-
`time="2020-08-25T14:18:36Z" level=warning msg="First line of log stream."`

opa logs-
https://gist.github.com/AnjaliRajan24/5ad41ed82eecbf5bcfef59e06f537669

**Comment by AnjaliRajan24** [comment]
@ashutosh-narkar @tsandall Would you know what is missing in here, I was able to get both validation and mutation webhooks to work independently but having this trouble only when I am trying to enable both of them.
Thanks!

**Comment by ashutosh-narkar** [comment]
@AnjaliRajan24 as the error says `var isCreateOrUpdate is unsafe`. You would need to define `isCreateOrUpdate` as you have in your original policy.

**Comment by AnjaliRajan24** [comment]
Hi @ashutosh-narkar, Yeah I can get mutation policy annotated as status-ok if I define `isCreateorUpdate` and `makeAnnotationPatch` in there like in main function but I don't see that in the tutorial https://github.com/open-policy-agent/library/blob/master/kubernetes/mutating-admission/example_mutation.rego

Also even though it gets annotated as status-ok, the policy is not getting enforced. It is not adding foo:bar as a label to the deployment. And weird, it is letting me create that deployment (Even though it is pulling images from wrong registry), as mentioned in validation policy I have. That means both val and mut policies are getting annotated but not getting enforced.

**Comment by AnjaliRajan24** [comment]
```
➜  helm-opa git:(KUBERNETES-5636) ✗ kc get cm foo-policy -n opa -o json | jq '.metadata'
{
  "annotations": {
    "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"data\":{\"admission-policy\":\"package library.kubernetes.admission.mutating\\npatch[patchCode]{\\n  isCreateOrUpdate\\n  input.request.object.metadata.annotations[\\\"test-mutation\\\"]\\n  patchCode = makeAnnotationPatch(\\\"add\\\", \\\"foo\\\", \\\"bar\\\", \\\"\\\")\\n}\\nisCreateOrUpdate { isCreate }\\nisCreateOrUpdate { isUpdate }\\nisCreate { input.request.operation == \\\"CREATE\\\" }\\nisUpdate { input.request.operation == \\\"UPDATE\\\" }\\n\\nmakeAnnotationPatch(op, key, value, pathPrefix) = patchCode {\\n  patchCode = {\\n    \\\"op\\\": op,\\n    \\\"path\\\": concat(\\\"/\\\", [pathPrefix, \\\"metadata/annotations\\\", replace(key, \\\"/\\\", \\\"~1\\\")]),\\n    \\\"value\\\": value,\\n  }\\n}\\n\"},\"kind\":\"ConfigMap\",\"metadata\":{\"annotations\":{},\"labels\":{\"openpolicyagent.org/policy\":\"rego\"},\"name\":\"foo-policy\",\"namespace\":\"opa\"}}\n",
    "openpolicyagent.org/policy-status": "{\"status\":\"ok\"}"
  },
  "creationTimestamp": "2020-08-25T19:32:48Z",
  "labels": {
    "openpolicyagent.org/policy": "rego"
  },
  "name": "foo-policy",
  "namespace": "opa",
  "resourceVersion": "92065660",
  "selfLink": "/api/v1/namespaces/opa/configmaps/foo-policy",
  "uid": "c92d4012-759f-48bd-8e12-c0efb089468a"
}

➜  helm-opa git:(KUBERNETES-5636) ✗ kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml -n norbert
deployment.apps/nginx-deployment created

➜  helm-opa git:(KUBERNETES-5636) ✗ kubectl label deployment nginx-deployment test-mutation=true
deployment.apps/nginx-deployment labeled

➜  helm-opa git:(KUBERNETES-5636) ✗ kubectl get deployment nginx-deployment -o json | jq '.metadata'
{
  "annotations": {
    "deployment.kubernetes.io/revision": "1",
    "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"nginx\"},\"name\":\"nginx-deployment\",\"namespace\":\"norbert\"},\"spec\":{\"replicas\":3,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.14.2\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}]}}}}\n"
  },
  "creationTimestamp": "2020-08-25T19:34:58Z",
  "generation": 1,
  "labels": {
    "app": "nginx",
    "test-mutation": "true"
  },
  "name": "nginx-deployment",
  "namespace": "norbert",
  "resourceVersion": "92067715",
  "selfLink": "/apis/apps/v1/namespaces/norbert/deployments/nginx-deployment",
  "uid": "f72f317a-2d59-4e99-b924-ee8d8e911e46"
}
➜  helm-opa git:(KUBERNETES-5636) ✗
```

**Comment by ashutosh-narkar** [comment]
It's defined [here](https://github.com/open-policy-agent/library/blob/master/kubernetes/mutating-admission/main.rego). Are you following [this](https://gist.github.com/tsandall/a9b2b57f7c6768f49b25271776b72dee) example ? Also note that by default `data.system.main` is used to serve policy queries.

**Comment by AnjaliRajan24** [comment]
Yup I am following [this](https://github.com/open-policy-agent/library/tree/master/kubernetes/mutating-admission) one. And My mutation policy is same as in [this](https://gist.github.com/tsandall/a9b2b57f7c6768f49b25271776b72dee) example, which add foo:bar as annotation if test-mutation:true is present.

**Comment by AnjaliRajan24** [comment]
Those functions that my mutation policy was erroring for was defined in my main https://gist.github.com/AnjaliRajan24/e99bd276cd1ee480eb59831899677c11#file-main-yaml-L55

**Comment by ashutosh-narkar** [comment]
What does your `MutatingWebhookConfiguration ` configuration look like ? Also have you unit tested your policy ?  I would highly recommend it to make sure the policy is doing what it's supposed to. It also makes debugging easier.

**Comment by AnjaliRajan24** [comment]
Here is my mutation webhook- https://gist.github.com/AnjaliRajan24/555c35ef569e65a7fbdc0d210f63ffbe#file-helm-opa-yaml-L442 (This is my template I am using to roll out opa)

**Comment by AnjaliRajan24** [comment]
I was able get mutation webhook to work independently when I was following along this example https://gist.github.com/tsandall/a9b2b57f7c6768f49b25271776b72dee

Here is an example of foo:bar getting added-
```
➜  helm-opa git:(KUBERNETES-5636) ✗ kubectl get deployment nginx-deployment -o json | jq '.metadata'
{
  "annotations": {
    "deployment.kubernetes.io/revision": "1",
    "foo": "bar", <--------------------------------------------
    "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"nginx\"},\"name\":\"nginx-deployment\",\"namespace\":\"norbert\"},\"spec\":{\"replicas\":3,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.14.2\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}]}}}}\n",
    "test-mutation": "true"
  },
  "creationTimestamp": "2020-08-13T05:18:48Z",
  "generation": 2,
  "labels": {
    "app": "nginx"
  },
  "name": "nginx-deployment",
  "namespace": "norbert",
  "resourceVersion": "82852403",
  "selfLink": "/apis/apps/v1/namespaces/norbert/deployments/nginx-deployment",
  "uid": "baad56d9-3403-4053-9b66-323bcef0e269"
}
```

**Comment by ashutosh-narkar** [comment]
You could try setting `path` in your webhook config for the validating and mutating controllers to point to a specific rule in the policy. See [this](https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/examples/istio/quick_start.yaml#L231) for reference.

**Comment by AnjaliRajan24** [comment]
Umm.. sorry but not really sure how to get the exact path here like ` path: "/v0/data/istio/inject"`?
Also, I plan on having multiple validations and mutation policies in the future. I am not fully understanding how pointing to a specific rule could help me with that.

**Comment by ashutosh-narkar** [comment]
If your mutation was working earlier, I would try to break setup in steps and check the OPA logs to see the decision generated. I suggested the `path` approach so that you could point the admission controller config to different entry points 
(ie. one for validation and other for mutation). You can have multiple policies for each and your top-level level policy would simply call the other policies and aggregate the results.

**Comment by AnjaliRajan24** [comment]
Ok so I tested it all again breaking into pieces and the mutation webhook works when I am following this [example](https://gist.github.com/tsandall/a9b2b57f7c6768f49b25271776b72dee) as is, but it is not working if I split the policy from main into a separate rego file. The policy gets annotated but not getting enforced. Also even if I have certain functions defined in main, policy is unable to read those until I define them in the policy rego file.

**Comment by ashutosh-narkar** [comment]
I would try using OPA's REST api to see the policies that are actually loaded and also look at the OPA logs to see the request and response. That would help to debug further.

**Comment by AnjaliRajan24** [comment]
So I have narrowed it down to these snippets. I am probably not specifying the packages correctly here - 
main
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: main
  namespace: {{ .Values.config.openpolicyagent.namespace }}
  labels:
    openpolicyagent.org/policy: rego

data:
  main: |
    package system
    import data.library.kubernetes.admission.mutating
    response_uid = input.request.uid
    main = {
      "apiVersion": "admission.k8s.io/v1beta1",
      "kind": "AdmissionReview",
      "response": response,
    }

```
policy
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo-policy
  namespace: {{ .Values.config.openpolicyagent.namespace }}
  labels:
    openpolicyagent.org/policy: rego

data:
  admission-policy: |
    package library.kubernetes.admission.mutating
    patch[patchCode]{
      isCreateOrUpdate
      input.request.object.metadata.annotations["test-mutation"]
      patchCode = makeAnnotationPatch("add", "foo", "bar", "")
    }
{{- end -}}
```
That is why my policy is not able to find functions defined in main.
But if I modify my main's package as  `package library.kubernetes.admission.mutating` instead of `package: system` then, policy is not able to find functions defined in main. But in that case, OPA logs get flooded with document missing `data.system.main`. What can I do to change query path OPA that evaluate `data.system.main` by default?

**Comment by ashutosh-narkar** [comment]
> You could try setting `path` in your webhook config for the validating and mutating controllers to point to a specific rule in the policy. See [this](https://github.com/open-policy-agent/opa-envoy-plugin/blob/master/examples/istio/quick_start.yaml#L231) for reference.

In your case it would be `path: "/v0/data/library/kubernetes/admission/mutating/main"`. Also in your main policy the `response` object does not refer to any rule so you may want to update that as well.

**Comment by AnjaliRajan24** [comment]
This is how my main cm, mutation policy  cm and validation policy cm looks now-
```
➜  helm-opa git:(KUBERNETES-5636) ✗ kc describe cm main -n opa
Name:         main
Namespace:    opa
Labels:       openpolicyagent.org/policy=rego
Annotations:  openpolicyagent.org/policy-status: {"status":"ok"}

Data
====
main:
----
package library.kubernetes.admission.mutating

main = {
  "apiVersion": "admission.k8s.io/v1beta1",
  "kind": "AdmissionReview",
  "response": response,
}

default response = {"allowed": true}

response = x {
  count(patch) == 0

  x := {
    "allowed": false,
    "status": {"reason": reason},
  }

  reason = concat(", ", deny)
  reason != ""
}

response = x {
  count(patch) > 0

  fullPatches := ensureParentPathsExist(cast_array(patch))

  x := {
    "allowed": true,
    "patchType": "JSONPatch",
    "patch": base64.encode(json.marshal(fullPatches)),
  }
}

isValidRequest { count(deny) == 0 }
isCreateOrUpdate { isCreate }
isCreateOrUpdate { isUpdate }
isCreate { input.request.operation == "CREATE" }
isUpdate { input.request.operation == "UPDATE" }

hasLabels(obj) { obj.metadata.labels }
hasLabel(obj, label) { obj.metadata.labels[label] }
hasLabelValue(obj, key, val) { obj.metadata.labels[key] = val }
hasAnnotations(obj) { obj.metadata.annotations }
hasAnnotation(obj, annotation) { obj.metadata.annotations[annotation] }
hasAnnotationValue(obj, key, val) { obj.metadata.annotations[key] = val }

makeLabelPatch(op, key, value, pathPrefix) = patchCode {
  patchCode = {
    "op": op,
    "path": concat("/", [pathPrefix, "metadata/labels", replace(key, "/", "~1")]),
    "value": value,
  }
}

makeAnnotationPatch(op, key, value, pathPrefix) = patchCode {
  patchCode = {
    "op": op,
    "path": concat("/", [pathPrefix, "metadata/annotations", replace(key, "/", "~1")]),
    "value": value,
  }
}

ensureParentPathsExist(patches) = result {
  paths := {p.path | p := patches[_]}
  missingPaths := {sprintf("/%s", [concat("/", prefixPath)]) |
    paths[path]
    pathArray := split(path, "/")
    pathArray[i] # walk over path
    i > 0 # skip initial element

    prefixPath := [pathArray[j] | pathArray[j]; j < i; j > 0]
    walkPath := [toWalkElement(x) | x := prefixPath[_]]
    not inputPathExists(walkPath) with input as input.request.object
  }

  ordered_paths := sort(missingPaths)
  new_patches := [{"op": "add", "path": p, "value": {}} | p := ordered_paths[_]]

  result := array.concat(new_patches, patches)
}

inputPathExists(path) { walk(input, [path, _]) }

toWalkElement(str) = str { not re_match("^[0-9]+$", str) }

toWalkElement(str) = x {
  re_match("^[0-9]+$", str)
  x := to_number(str)
}

deny[msg] {
  input.request.kind == "AdmissionReview"
  msg = "Input must be Kubernetes AdmissionRequest"
}

patch[patchCode] {
  input.kind == "ThisHadBetterNotBeARealKind"
  patchCode = {}
}

Events:  <none>
```
```
➜  helm-opa git:(KUBERNETES-5636) ✗ kc describe cm foo-policy -n opa
Name:         foo-policy
Namespace:    opa
Labels:       openpolicyagent.org/policy=rego
Annotations:  openpolicyagent.org/policy-status: {"status":"ok"}

Data
====
admission-policy:
----
package library.kubernetes.admission.mutating
patch[patchCode]{
  isCreateOrUpdate
  input.request.object.metadata.annotations["test-mutation"]
  patchCode = makeAnnotationPatch("add", "foo", "bar", "")
}

Events:  <none>
```
```
➜  helm-opa git:(KUBERNETES-5636) ✗ kc describe cm admission-policy -n opa
Name:         admission-policy
Namespace:    opa
Labels:       openpolicyagent.org/policy=rego
Annotations:  openpolicyagent.org/policy-status: {"status":"ok"}

Data
====
admission-policy:
----
package library.kubernetes.admission.mutating

operations = {"CREATE", "UPDATE"}

deny[reason] {
  some container
  input_containers[container]
  not startswith(container.image, "docker-secure.cernerrepos.net")
  reason := sprintf("Container '%s' should be from registry 'docker-secure.cernerrepos.net'", [container.name])
}

input_containers[c] {
  c := input.request.object.spec.containers[_]
}

input_containers[c] {
  c := input.request.object.spec.template.spec.containers[_]
}

Events:  <none>
```

In this case OPA logs complain
```
[INFO] Sent response.
  resp_body = |
      {
        "code": "undefined_document",
        "message": "document missing or undefined: data.system.main"
      }


  client_addr = "192.168.24.23:30002"
  req_id = 10
  req_method = "POST"
  req_path = "/"
  resp_status = 404
  resp_bytes = 99
  resp_duration = 6.448214

[INFO] Sent response.
  resp_body = |
      {
        "code": "undefined_document",
        "message": "document missing or undefined: data.system.main"
      }
```

Adding path to webhook configuration resulting in 
```
W0826 23:46:49.447518       1 dispatcher.go:168] Failed calling webhook, failing open webhook.openpolicyagent.org: failed calling webhook "webhook.openpolicyagent.org": the server has asked for the client to provide credentials
E0826 23:46:49.447545       1 dispatcher.go:169] failed calling webhook "webhook.openpolicyagent.org": the server has asked for the client to provide credentials
```

I also tried adding 
`--set default_decision=data.library.kubernetes.admission.mutating.main` to opa container arg but that resulted in pods erroring out and going into back-off state

**Comment by AnjaliRajan24** [comment]
Here is my testing so far, if I run 
```
./opa run --server ./main.rego
```
I get 
```
➜  ~ curl -X POST  localhost:8181/
{
  "code": "undefined_document",
  "message": "document missing or undefined: data.system.main"
}
```
but if I include `--set default_decision`
```
➜  ./opa run --server --set default_decision=library.kubernetes.admission.mutating.main ./main.rego

```

```
➜  ~ curl -X POST  localhost:8181/
{"apiVersion":"admission.k8s.io/v1beta1","kind":"AdmissionReview","response":{"allowed":true,"uid":""}}%                                                                                                                                      ➜  ~
```

I am not exactly sure where to include `--set default_decision`, I included it in OPA deployment args but that is causing my containers to go into backoff.

**Comment by ashutosh-narkar** [comment]
How does your mutating and validating config look like ? I thought you are using the `path` field to query for a particular policy decision.  By default `data.system.main` is used to serve policy queries without a path but since your config specifies one, you should be good. Also verify that the CA bundle specified in the validating or mutating webhook configurations matches the server certificate you configured OPA to use.

**Comment by AnjaliRajan24** [comment]
```
# Source: opa/templates/webhook-configuration.yaml
kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa
  namespace: opa
  annotations:
  labels:
    app: opa
    chart: "opa-1.13.11-SNAPSHOT"
    release: "RELEASE-NAME"
    heritage: "Helm"
webhooks:
  - name: webhook.openpolicyagent.org
    namespaceSelector:
      matchExpressions:
      - key: openpolicyagent.org/webhook
        operator: NotIn
        values:
        - ignore

    failurePolicy: Ignore
    rules:
      - apiGroups:
        - '*'
        apiVersions:
        - '*'
        operations:
        - '*'
        resources:
        - '*'
    clientConfig:


      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQWV1Z0F3SUJBZ0lSQUtidmNWQ1pOWWFCellqTHJKdHU1NDB3RFFZSktvWklodmNOQVFFTEJRQXcKR3pFWk1CY0dBMVVFQXhNUWIzQmhMV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlNREE0TWpjd016QTFNemxhRncwegpNREE0TWpVd016QTFNemxhTUJzeEdUQVhCZ05WQkFNVEVHOXdZUzFoWkcxcGMzTnBiMjR0WTJFd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdHB6WmZFWDdDVXJDZENVb0JRVXo5aWNHTVk3a1EKL3owTk4rZFBtTHFPN1JIY2c1KzFZVE1HUlRYTm9CUTdSQVhoK0hCVXN2dW1JZlAzMXZZbWlkSlhCcElkYzlSagpEeGpUek5laWsyRVpUdzYySTBMVjZpc0F0bEVZTlZaQU9aQnBoR2tHbGF2UGdCUVNrUkEwVjVZaGRhcXZRMmtLClc1d3M0d0pBWlVqMEtDckFURE1oREhCSTlBbGxldmJWeDFhZTI3ekNZTUJ5R2dIL2tibXRrN2lyNmpKZ1VOWlYKbmFxM3E4bXdPRkNmY3pZY1NNMjk2WUNkZHpIZjIybDZXNjFqb0xhdDJTT0xZYkF1UmhDdFJBZEorTEM3SGdkMQpLMUZJV096cWI4WE9sNFJDSGhRZURYNCsrSm5VOFhPR0ZtWlhXUjV0R0FaS3dONEI5alk2SU1RYkFnTUJBQUdqClFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUkrKzF2VnNoY0I4egpTdkVJMmtzYlUzUzR2VHFURml3dnRDcCs3WGRUQUdnc0hnVFpRK290bUtsTVEwa2Zma0loZDE4cHBueWFWVzhFCkw0Vmx3WU1ORG1ZVkpBSXRjNTBGMUJJWXRhd3l3UlVMK0N6ZXVBQWVzNEN5NXJhN1ZUbVVGU20wMnZVbmNBTFgKaHJKM1EwTXBqcmJEOVRmczlBQldpUG9kemgrSlBmbU9xRTd5OU56NUxoRktKMEMwa0lrMnFBVi93cXFqVHpuQwpxVEM1UnhhbVZ2bWFJeUdOOUwxd3JzcUpQS3pjZjkvZjJ5SzFnbEhhZ202SEIxVjFrNTl4TmduOEhBWGd0dDNOClF6MkFPem9VbnZzRGt2NHUzbGVsR29ETHpua251NUhKandlZUxhd3ZCWFU5WmlHTmY1R1ZHb1F5WUhtNm1xYm0KK25DY0FIWitxQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K


      service:
        name: opa
        namespace: opa
    sideEffects: Unknown
---
# Source: opa/templates/webhook-configuration.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa
  namespace: opa
  annotations:
  labels:
    app: opa
    chart: "opa-1.13.11-SNAPSHOT"
    release: "RELEASE-NAME"
    heritage: "Helm"
webhooks:
  - name: webhook.openpolicyagent.org
    namespaceSelector:
      matchExpressions:
      - key: openpolicyagent.org/webhook
        operator: NotIn
        values:
        - ignore

    failurePolicy: Ignore
    rules:
      - apiGroups:
        - '*'
        apiVersions:
        - '*'
        operations:
        - '*'
        resources:
        - '*'
    clientConfig:


      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBekNDQWV1Z0F3SUJBZ0lSQUtidmNWQ1pOWWFCellqTHJKdHU1NDB3RFFZSktvWklodmNOQVFFTEJRQXcKR3pFWk1CY0dBMVVFQXhNUWIzQmhMV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlNREE0TWpjd016QTFNemxhRncwegpNREE0TWpVd016QTFNemxhTUJzeEdUQVhCZ05WQkFNVEVHOXdZUzFoWkcxcGMzTnBiMjR0WTJFd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdHB6WmZFWDdDVXJDZENVb0JRVXo5aWNHTVk3a1EKL3owTk4rZFBtTHFPN1JIY2c1KzFZVE1HUlRYTm9CUTdSQVhoK0hCVXN2dW1JZlAzMXZZbWlkSlhCcElkYzlSagpEeGpUek5laWsyRVpUdzYySTBMVjZpc0F0bEVZTlZaQU9aQnBoR2tHbGF2UGdCUVNrUkEwVjVZaGRhcXZRMmtLClc1d3M0d0pBWlVqMEtDckFURE1oREhCSTlBbGxldmJWeDFhZTI3ekNZTUJ5R2dIL2tibXRrN2lyNmpKZ1VOWlYKbmFxM3E4bXdPRkNmY3pZY1NNMjk2WUNkZHpIZjIybDZXNjFqb0xhdDJTT0xZYkF1UmhDdFJBZEorTEM3SGdkMQpLMUZJV096cWI4WE9sNFJDSGhRZURYNCsrSm5VOFhPR0ZtWlhXUjV0R0FaS3dONEI5alk2SU1RYkFnTUJBQUdqClFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUkrKzF2VnNoY0I4egpTdkVJMmtzYlUzUzR2VHFURml3dnRDcCs3WGRUQUdnc0hnVFpRK290bUtsTVEwa2Zma0loZDE4cHBueWFWVzhFCkw0Vmx3WU1ORG1ZVkpBSXRjNTBGMUJJWXRhd3l3UlVMK0N6ZXVBQWVzNEN5NXJhN1ZUbVVGU20wMnZVbmNBTFgKaHJKM1EwTXBqcmJEOVRmczlBQldpUG9kemgrSlBmbU9xRTd5OU56NUxoRktKMEMwa0lrMnFBVi93cXFqVHpuQwpxVEM1UnhhbVZ2bWFJeUdOOUwxd3JzcUpQS3pjZjkvZjJ5SzFnbEhhZ202SEIxVjFrNTl4TmduOEhBWGd0dDNOClF6MkFPem9VbnZzRGt2NHUzbGVsR29ETHpua251NUhKandlZUxhd3ZCWFU5WmlHTmY1R1ZHb1F5WUhtNm1xYm0KK25DY0FIWitxQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K


      service:
        name: opa
        namespace: opa
    sideEffects: Unknown

```
