### ISSUE TITLE
Can not run command 

### ISSUE THREAD

**Issue by sanchetanparmar** [open-policy-agent/opa#2871]
Deployed OPA on K8s 
deployments file 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:latest
        ports:
        - name: http
          containerPort: 8181
        args:
        - "run"
        - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
        - "--server"
        - "/policies"
         command: ["/bin/bash", "-c", "echo Hello from the postStart handler > /usr/share/message"]
        volumeMounts:
        - readOnly: true
          mountPath: /policies
          name: example-policy
      volumes:
      - name: example-policy
        configMap:
          name: example-policy
```
I am not able to run shell commands - 
`command: ["/bin/bash", "-c", "echo Hello from the postStart handler > /tmp/message"]`

Tried with `ash` `/bin/ash` `sh ``/bin/sh` `bash` `bin/bash` same error for all. 

**Error** - `Error: failed to start container "opa": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/bin/ash": stat /bin/ash: no such file or directory: unknown`

How can i rebuild to run command in pods ?
