### ISSUE TITLE
Envoy Filters not forwarding the requests to OPA using istio 1.7

### ISSUE THREAD

**Issue by hxn36** [open-policy-agent/opa#2973]
## Expected Behavior

OPA to deny/allow requests based on defined policies.

## Actual Behavior
OPA server not receiving any requests using the below enovyFilter
``` 
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: opa-ext-authz
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            transport_api_version: V3
            status_on_error:
              code: ServiceUnavailable
            with_request_body:
              max_request_bytes: 8192
              allow_partial_message: true
            grpc_service:
              # NOTE(tsandall): when this was tested with the envoy_grpc client the gRPC
              # server was receiving check requests over HTTP 1.1. The gRPC server in
              # OPA-Istio would immediately close the connection and log that a bogus
              # preamble was sent by the client (it expected HTTP 2). Switching to the
              # google_grpc client resolved this issue.
              google_grpc:
                target_uri: 127.0.0.1:9191
                stat_prefix: "ext_authz" 
```

## Steps to Reproduce the Problems

Deployed sample nginx hellow world program with Istio 1.7 and OPA v21.0 using the above EnvoyFilter

## Additional Info
istio_config_dump:
``` 
{
              "name": "envoy.ext_authz",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
               "grpc_service": {
                "google_grpc": {
                 "target_uri": "127.0.0.1:9191",
                 "stat_prefix": "ext_authz"
                }
               },
               "with_request_body": {
                "max_request_bytes": 8192,
                "allow_partial_message": true
               },
               "status_on_error": {
                "code": "ServiceUnavailable"
               },
               "transport_api_version": "V3"
              }
             },
             {
              "name": "envoy.filters.http.router",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
              }
             } 
```

**Comment by ashutosh-narkar** [comment]
Can you try using a more recent version of the plugin. For example `v0.25.0-envoy` which was released today !

**Comment by hxn36** [comment]
Deployed the latest version, still same issue. Unable to send requests to OPA server.

**Comment by ashutosh-narkar** [comment]
It would be helpful if you could provide any Envoy (Istio-proxy) logs, the platform you are running this on and any other relevant details to help debug/repro the issue.

**Comment by hxn36** [comment]
We are running all our workloads on GKE(1.17.12-gke.1504). I have used istio 1.7 and opa v0.25.0-envoy.  I have already pasted the envoyfilter above. Please let me know if you need more info. Thanks.
[proxy_logs.txt](https://github.com/open-policy-agent/opa/files/5640742/proxy_logs.txt)
[opa_logs.txt](https://github.com/open-policy-agent/opa/files/5640747/opa_logs.txt)

**Comment by srenatus** [comment]
Recapping this, for using the v3 API,
```
          name: envoy.ext_authz
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            transport_api_version: V3
```
you definitely need version 0.25.0 of the plugin. (It still supports the v2 API, too, though, so you could go with v2. Please take note of the v2-to-v3 migration notes here: https://github.com/open-policy-agent/opa-envoy-plugin#envoy-xds-v2-and-v2)

So could you please double check that your sidecars are really using the v0.25.0-envoy container? If they didn't, it would silently fail in the way you've described here, any opa-envoy-plugin container of an older version would respond with 503 and not log anything if asked for a Check using the v3 API (this is due to how golang's gRPC library works).

**Comment by hxn36** [comment]
I have tried with v2 API as well, still the same issue. The requests itself are not being forwarded to OPA server. I believe something wrong the envoyfilters.
istio_config_dump:
```
{
              "name": "envoy.ext_authz",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz",
               "grpc_service": {
                "google_grpc": {
                 "target_uri": "127.0.0.1:9191",
                 "stat_prefix": "ext_authz"
                }
               },
               "with_request_body": {
                "max_request_bytes": 8192,
                "allow_partial_message": true
               },
               "status_on_error": {
                "code": "ServiceUnavailable"
               }
              }
             },
             {
              "name": "envoy.filters.http.router",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
              }
             }
```
I have used the latest opa `v0.25.0-envoy`

**Comment by ashutosh-narkar** [comment]
@hxn36 I tried using the latest version of the plugin (`0.25.0-istio`) with Istio `v1.8.0` on minikube (`k8s version: v1.18.0`) with the Envoy  v2 api. Below is the Envoy filter config. The [Bookinfo example](https://github.com/open-policy-agent/opa-envoy-plugin/tree/master/examples/istio#quick-start) works as expected and OPA gets the authz request from Envoy. One of the differences between our setup is you're running this on GKE. It could be possible that Envoy can't reach OPA. Have you seen any other logs that could help debug this ? Also what does your deployment manifest look like ? 

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          typed_config:
            "@type": "type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz"
            status_on_error:
              code: ServiceUnavailable
            with_request_body:
              max_request_bytes: 8192
              allow_partial_message: true
            grpc_service:
              google_grpc:
                target_uri: 127.0.0.1:9191
                stat_prefix: "ext_authz"
```

**Comment by hxn36** [comment]
Hi Ash, Naming the service port fixed the issue. Thanks for the help, closing this issue!

**Comment by mohsalsaleem** [comment]
@hxn36 Could you please elaborate what you meant by naming the service port? I'm currently facing the same issue and it'll be of great help.

**Comment by h2ho** [comment]
Took me a few minutes to figure it out.
``` yaml
spec:
  ports:
  - name: http  #http 
    port: 8080
    protocol: TCP
    targetPort: http

```
