### ISSUE TITLE
OPA 0.21.1 onward not working on EC2 environment due to 

### ISSUE THREAD

**Issue by zacyang** [open-policy-agent/opa#2975]
We are using OPA in EC2 running as docker container in our prod.
When we upgrade to 0.24.0 docker image, we got issue
```
{"level":"error","msg":"Bundle download failed: request failed: error getting AWS credentials: metadata token HTTP request failed: Put http://169.254.169.254/latest/api/token: net/http: request canceled (Client.Timeout exceeded while awaiting headers)","name":"xxx","plugin":"bundle","time":"2020-12-03T10:17:10Z"}
```

we are using bunlde configuration, 2 bunldes are stored in s3, with 
signning enabled:
```
    credentials:
      s3_signing:
        metadata_credentials:
          aws_region: ${AWS_REGION}
          iam_role: ${IAM_ROLE}
```

while trying out different versions, we have identified the issue exists 0.21.1 onward (exclude 0.21.1)

## Expected Behavior
Able to call EC2 meta endpoint to get role info so we can load bundles in s3

## Steps to Reproduce the Problem
1. start opa as a docker container in ec2 version > 0.21.1
2. use configure with s3 signning 
3. cli will prompt the same error
