### ISSUE TITLE
Cannot increase request size

### ISSUE THREAD

**Issue by konstantin-tkachuk** [open-policy-agent/opa#2977]
## Expected Behavior
I want to configure the max request size which is allowed before Envoy rejects it with a 413. I have looked at this:
https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/flow_control
and attempted to add the necessary configuration, but it didn't work.

## Actual Behavior
I get 413 as soon as the request is bigger than 1 MB.

## Steps to Reproduce the Problem
I am using the setup from here:
https://www.openpolicyagent.org/docs/latest/envoy-authorization/

I adjusted the envoy config in the following way, but it doesn't seem to do _anything_.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: navigation-service-envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
        **per_connection_buffer_limit_bytes: 4000000**
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8000
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
              **http2_protocol_options:
                initial_stream_window_size: 4000000**
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: service
              http_filters:
              - name: envoy.ext_authz
                typed_config:
                  "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
                  with_request_body:
                    **max_request_bytes: 4000000**
                    allow_partial_message: true
                  failure_mode_allow: false
                  grpc_service:
                    google_grpc:
                      target_uri: 127.0.0.1:9191
                      stat_prefix: ext_authz
                    timeout: 0.5s
              - name: envoy.router
                typed_config: {}
      clusters:
        **per_connection_buffer_limit_bytes: 4000000**
        name: service
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        load_assignment:
          cluster_name: service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8080
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
```
