### ISSUE TITLE
Make it easier to pull in OPA in Github Actions

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3014]
## Expected Behavior

In order to use OPA in a Github Actions workflows, I'd like to be able to do something like this:
```yaml
- uses: openpolicyagent/setup-opa@v1
  with:
    opa-version: '^0.25.2'

# ...subsequent tasks using OPA here
```
with niceties like caching etc provided by the action. 

("inspired" by the [setup-go](https://github.com/actions/setup-go) action)

## Actual Behavior

Everyone having to manually download OPA, keep track of versions, handle caching, etc.. themselves.

**Comment by tsandall** [comment]
I'm not familiar with implementing actions. Would this be another artifact we have to publish with each release or can it be decoupled from the OPA release cycle. Obviously it would be nice not to have to build and publish another artifact.

**Comment by srenatus** [comment]
Here are the sources for the setup-go action: https://github.com/actions/setup-go/blob/main/src/installer.ts -- tl;dr: the version to be installed will be input to the script, there's no extra artifact to provide when releasing, as long as we keep the structures intact (`https://github.com/open-policy-agent/releases/v${ver}/tarball/yadda/yadda`).

**Comment by srenatus** [comment]
One thing -- I can _imagine_ finding this useful, but having some actual feedback from the community would be great. Perhaps we can post this issue in Slack to gauge interest? 🤔

**Comment by anderseknert** [comment]
That OPA itself is useful as part of CI/CD pipelines is pretty much implied in this context, no? 😄 

All this would do is to remove some of the current ceremony around that. IMO, we don't really need to look outside [our](https://github.com/open-policy-agent/contrib/blob/master/build/install-opa.sh) [own](https://github.com/open-policy-agent/npm-opa-wasm/blob/master/.github/workflows/ci.yml#L22) [repositories](https://github.com/open-policy-agent/library/blob/master/build/test.sh) to see how this is useful, but if we do I have at least 5-6 personal repos where this would be desirable too.

**Comment by srenatus** [comment]
😄 You're quite right. Let's do this. 🚀

**Comment by srenatus** [comment]
I've learnt recently that you don't need to use JS for actions; you can create "composite actions" that are basically shell script steps. This should make this a low-hanging fruit, shouldn't it?

**Comment by anderseknert** [comment]
My understanding of composite actions is basically that they allow you to extract a common task, and reuse that across other tasks and files. I'm not sure whether they can be "exported" to the Github marketplace.

**Comment by srenatus** [comment]
I could be wrong, but from the docs, https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace, it _seems_ to be like "javascript actions" and "composite actions" were equals. That said, any more complicated feature will likely require JS (or TS) anyways.

**Comment by Hongbo-Miao** [comment]
Just add more info in case it helps design this one.

For me, I am currently using like

```yml
  opa-test:
    name: OPA - Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download OPA Binary
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod 755 ./opa
      - name: Test
        run: |
          ./opa test policies/*.rego -v
```

There is a third-party GitHub Action, basically doing same thing underneath: https://github.com/petroprotsakh/opa-test-action

**Comment by ribbybibby** [comment]
For even greater brevity, you can use the `openpolicyagent/opa` docker image directly:
```yaml
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://openpolicyagent/opa
        with:
          args: "test --ignore=*.yaml --ignore=*.json -v policies"
```
