### ISSUE TITLE
bundles: Signature verification triggered by presence of keys, even if not referenced

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3028]
## Expected Behavior

As stated in the docs, bundle signature verification should not be performed unless a key is referenced in a bundle configuration block.

> Signature verification fails if the bundles[_].signing field is configured on a bundle but no .signatures.json file is included in the actual bundle gzipped tarball.

## Actual Behavior

Merely the presence of a `keys` block will trigger signature verification, even if no key is referenced by the bundle. Example:

```yaml
bundles:
  authz:
    service: aws
    resource: bundles/policy.tar.gz
  # no "signing" block here

keys:
  secret:
    key: abc123
    algorithm: HS256
```

Results in:

```
{"level":"error","msg":"Bundle download failed: bundle missing .signatures.json file","name":"authz","plugin":"bundle","time":"2020-12-21T23:51:39Z"}
```

## Steps to Reproduce the Problem

See above configuration.
