### ISSUE TITLE
Extend OAuth2 credentials module to support JWT authorization grant

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3055]
While the original OAuth2 specification details using `client_id`/`client_secret` to authenticate the client in the `client_credentials` flow, [rfc7523](https://tools.ietf.org/html/rfc7523) offers an alternative where the client crafts a JWT which it signs and sends to the token endpoint as its credential rather than a secret. While this approach adds a fair amount of complexity to the client implementation compared to just sending a password, it has the benefit of allowing the server to avoid dealing with secrets as all that is needed for verification is the public key component of the signing key.

One notable application of this method is Google Cloud Platform, which requires [service-to-service clients to authenticate](https://developers.google.com/identity/protocols/oauth2/service-account#httprest) this way in order to obtain access tokens for use to e.g. pull data from Google Cloud Storage.

Given how this is a standards-based approach (and Google from what I can see follows the standard without proprietary additions), it would be good to extend the OAuth2 authenticator to support this alternative mechanism, for GCP as much as any other standards compliant token issuer. Since the details of what claims is expected to be in the token, I would suggest we provide a map configuration option where anything is allowed, and that these claims are added to any token issued on top of some standard ones which we will need to set in code (such as issued at, `iat`). 

Example configuration for GCP:

```yaml
services:
  gcp:
    url: ${BUNDLE_SERVICE_URL}
    credentials:
      oauth2:
        grant_type: jwt_bearer
        signing_key: ${BUNDLE_SERVICE_SIGNING_KEY}
        scopes:
        - https://www.googleapis.com/auth/devstorage.read_only
        additional_claims:
          aud: https://oauth2.googleapis.com/token
          iss: opa-client@opa-lab.iam.gserviceaccount.com
```

An additional option is to provide a GCP specific option to the above, which would remove a few lines of above configuration since the values would be known by the plugin (grant_type, scopes and aud) but I think covering the GCP example case in the docs like this should be enough to start with.
