### ISSUE TITLE
Log decisions for Compile API

### ISSUE THREAD

**Issue by deepuec** [open-policy-agent/opa#3062]
## Expected Behavior
Logs uploaded to the /logs api provided
## Actual Behavior
Logs skipped with below message in console
{"level":"info","msg":"Log upload skipped.","plugin":"decision_logs","time":"2021-01-13T18:46:28+05:30"}

* OPA version 0.25.2

## Additional Info
I am using below config file as below with command opa run -s -c config.yml
When I run this in my windows machine, I am able to see both status and logs APIs receiving data. But when I push this into PCF container and run it as sidecar to spring microservice, it is able to download bundle file, make status API call. But not making decision API calls and able to see Log Upload Skipped message in the console even there are multiple decisions taken by the opa.

Let me know if I need to configure anything to get decision logs through API.
```
services:
  policydist:
    url: https://SERVER/v1/api
    response_header_timeout_seconds: 60
  policyserver:
    url: https://SERVER/v2/api
    response_header_timeout_seconds: 60
    credentials:
        oauth2:
            client_id: 
            client_secret: 
            token_url: 
            scopes: 

labels:
  app: testing
  region: south
  environment: dev

bundles:
  authz:
    service: policydist
    resource: services/bundles/latest
    persist: true
    polling:
      min_delay_seconds: 3000
      max_delay_seconds: 12000

decision_logs:
  service: policyserver
  reporting:
    min_delay_seconds: 30
    max_delay_seconds: 120

status:
  service: policyserver
```

Thank You for your help
