### ISSUE TITLE
How to use image for Gitlab job that requires a shell in it

### ISSUE THREAD

**Issue by developer-guy** [open-policy-agent/opa#3134]
## Expected Behavior
I just want to use opa as an image for my Gitlab Job like the following:
```yaml
static-analyze:
  stage: Static Analyze Rego files
  image:
    name: test.registry.com/openpolicyagent/opa:0.26.0
  script:
    - opa check $POLICY_DIR
  when: manual
```
## Actual Behavior
Once, I started this job it throws me an error like the following:
```bash
unknown command "sh" for "opa"
Error: unknown command "sh" for "opa"
Run 'opa --help' for usage.
```

**Comment by developer-guy** [comment]
So, i need to do some workaround to fix this such as creating new docker image based on alpine and install proper opa binary to it.
```Dockerfile
FROM alpine:3.13

ENV OPA_VERSION=v0.26.0

RUN apk update --no-cache && apk add -y --no-cache \
        wget

# Install open-policy-agent/opa
RUN mkdir -p /tmp/opa \
    && wget -O /tmp/opa/opa_linux_amd64 https://github.com/open-policy-agent/opa/releases/download/${OPA_VERSION}/opa_linux_amd64 \
    && mv /tmp/opa/opa_linux_amd64 /usr/local/bin/opa \
    && chmod +x /usr/local/bin/opa \
    && rm -rf /tmp/opa
```

**Comment by srenatus** [comment]
Hi, thanks for writing this up!

One thing that comes to mind is using the debug image, see https://github.com/open-policy-agent/opa/issues/1789.

Anyhow, I think if you switch from `script` to something that lets you benefit from the OPA container's entrypoint, you should be able to use the "orginary" (not :debug) images 🤔

**Comment by developer-guy** [comment]
> Hi, thanks for writing this up!
> 
> One thing that comes to mind is using the debug image, see #1789.
> 
> Anyhow, I think if you switch from `script` to something that lets you benefit from the OPA container's entrypoint, you should be able to use the "orginary" (not :debug) images 🤔

Nothing changed with debug images on Gitlab environment, same error happens :/
```yaml
static-analyze:
  stage: Static Analyze Rego files
  image:
    name: test.registry.com/openpolicyagent/opa:0.26.0-debug
  script:
    - opa check $POLICY_DIR
  when: manual
```

```bash
Executing "step_script" stage of the job script
unknown command "sh" for "opa"
Error: unknown command "sh" for "opa"
Run 'opa --help' for usage.
ERROR: Job failed: exit code 1
FATAL: exit code 1
```

**Comment by srenatus** [comment]
Can you try switching from script to something else? From that output, `script: ...` seems to expect that `docker run openpolicyagent/opa:0.26.0-debug sh` works, but that doesn't work **because the image's entrypoint is opa**, and `opa sh` is not a thing:
```
unknown command "sh" for "opa"
```

You could try to override the image's entrypoint **or** you could try some sort of command-style invocation, so that it ends up running `docker run openpolicyagent/opa:0.26.0 check $POLICY_DIR`. I haven't used gitlab recently, so I can't provide you with more detailed steps... 🐾

**Comment by anderseknert** [comment]
Looking at the [Gitlab docs](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#available-settings-for-image) it seems possible to override the entrypoint like @srenatus suggests:

```yaml
static-analyze:
  stage: Static Analyze Rego files
  image:
    name: test.registry.com/openpolicyagent/opa:0.26.0
    entrypoint:
      - opa
      - check
      - $POLICY_DIR
```

**Comment by srenatus** [comment]
Couldn't get any of the approaches I thought about to work.

👉 I think what you do there, https://github.com/open-policy-agent/opa/issues/3134#issuecomment-775887864, is the best thing that can be done right now: build a simple little image yourself, and run with that.

**Comment by anderseknert** [comment]
Yeah, their jobs pipeline seems to assume a docker image is provided to either execute a script (which obviously OPA is not) or to be run as a service (like postgres) to support later script tasks.  So while you could run OPA as a background service it doesn't make sense for the check task. Better then to just skip docker altogether. This works fine:

```yaml
opa_check:
  before_script:
    - curl --location --output opa https://github.com/open-policy-agent/opa/releases/download/v0.26.0/opa_linux_amd64
    - chmod +x opa
  script: ./opa check $POLICY_DIR'
```

**Comment by developer-guy** [comment]
thank you sou much for your help @anderseknert @srenatus 🙏

**Comment by sumsumbee** [comment]
Hey there, after some try and error i figured a working solution with the latest debug image:

```
static-analyze:
    stage: validate-rego
    image:
      name: openpolicyagent/opa@sha256:4f80a2a8875b9925020efe69e0399f1f4af457628f1284ff73d343ef3033f03a
      entrypoint: [""]
    script: ["/opa check $POLICY_DIR"]
```
