### ISSUE TITLE
oauth2: handle quirks with Azure JWT credentials

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3372]
While the regular client secret option for client credentials authentication works well with Azure, they also provide the option to use a signed JWT for auth as supported by OPA since before. This implementation however adds quite a few extra requirements not currently supported. A working configuration would look something like the below.

```yaml
keys:
  blob_key:
    algorithm: RS256
    private_key: "${PRIVATE_KEY}"

services:
  blob:
    url: https://opa.blob.core.windows.net
    headers:
      x-ms-version: "2020-04-08"
    credentials:
      oauth2:
        token_url: "https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token"
        signing_key: blob_key
        include_jti_claim: true
        scopes:
          - https://storage.azure.com/.default
        additional_claims:
          aud: "https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token"
          iss: "${CLIENT_ID}"
          sub: "${CLIENT_ID}"

bundles:
  authz:
    service: blob
    resource: opa/bundle.tar.gz
```

The first problem here is that Azure expects a `x5t` claim in the header, which is a base64url encoded represenatation of the SHA-1 encoded thumbprint of the certificate (found under Certificates and Secrets in the Azure console for any given AD app). <del>The next problem is that Azure responds with `Client assertion audience claim does not match Realm issuer` for the above configuration, and I have not managed to find what the expected audience value would be for the request.</del>

Not suggesting we work on this anytime soon, but mainly creating issue for tracking interest and to document my findings should we pick it up at some later point in time.
