### ISSUE TITLE
Failed to save new bundle to disk: mkdir /app/.opa: permission denied

### ISSUE THREAD

**Issue by AvniWala-Sophos** [open-policy-agent/opa#3438]
- OPA Version: v0.28.0-envoy

- OPA is running as a pod in Kubernetes (K3S version: v1.19.7+k3s1)

- The pods are installed using helm and we have security context configured. Relevant snippet of helm chart yaml file is as follows:

```
spec:
  replicas: {{ .Values.opa.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.opa.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.opa.name }}
    spec:
      securityContext:
        runAsUser: 5000
        runAsGroup: 5000
        runAsNonRoot: true
      hostname: {{ .Values.opa.name }}
```

## Expected Behavior
**Kindly suggest if there is a way to run rootless opa (with envoy plugin)**

## Actual Behavior
Getting following error messages in opa logs:

```
{"level":"error","msg":"Persisting bundle to disk failed: mkdir /app/.opa: permission denied","name":"authz","plugin":"bundle","time":"2021-05-06T11:53:32Z"}
{"level":"error","msg":"Failed to save new bundle to disk: mkdir /app/.opa: permission denied","name":"authz","plugin":"bundle","time":"2021-05-06T11:53:45Z"}
{"level":"error","msg":"Failed to remove temp file ('/app/.opa/bundles/authz/.bundle.tar.gz.tmp'): remove /app/.opa/bundles/authz/.bundle.tar.gz.tmp: no such file or directory","name":"authz","plugin":"bundle","time":"2021-05-06T11:53:45Z"}
```

**Comment by anderseknert** [comment]
Hi @AvniWala-Sophos ! 

What does your OPA configuration look like? OPA should not persist bundles by default, but can do so if configured with `persist: true` on the [bundles configuration object](https://www.openpolicyagent.org/docs/latest/configuration/#bundles). This obviously requires write access to the bundle persistence directory, which you can [configure](https://www.openpolicyagent.org/docs/latest/configuration/#miscellaneous) to your liking.

**Comment by AvniWala-Sophos** [comment]
> Hi @AvniWala-Sophos !
> 
> What does your OPA configuration look like? OPA should not persist bundles by default, but can do so if configured with `persist: true` on the [bundles configuration object](https://www.openpolicyagent.org/docs/latest/configuration/#bundles). This obviously requires write access to the bundle persistence directory, which you can [configure](https://www.openpolicyagent.org/docs/latest/configuration/#miscellaneous) to your liking.

Thanks @anderseknert . I do have persist: true. Below is my configuration. 

Earlier I was using v0.20.4 and things were working without any explicit persistence_directory configurations.  But I will mount a volume and provide that as persistence_directory. Hopefully that will work?. Thanks again!


```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.opa.name }}-config"
  namespace: {{ .Values.namespace }}
  labels:
    config: "{{ .Values.opa.name }}-config"
data:
  config.yaml: |
    services:
       - name: bundlecontroller
         url: http://{{ .Values.controlplane.name }}:{{ .Values.controlplane.ports.httpPort }}/policy
    bundles:
        authz:
          service: bundlecontroller
          resource: {{ .Values.opa.bundleName }}
          persist: true
          polling:
            min_delay_seconds: {{ .Values.opa.BUNDLE_POLL_MIN }}
            max_delay_seconds: {{ .Values.opa.BUNDLE_POLL_MAX }}
    plugins:
         envoy.ext_authz.grpc:
           addr: :{{ .Values.opa.ports.grpcPort }}
           query: data.envoy.authz.allow
```
