### ISSUE TITLE
envoy opa plugin log messages

### ISSUE THREAD

**Issue by justincely** [open-policy-agent/opa#3566]
## Expected Behavior
When using the envoy plugin: `package envoy.authz` I wasn't seeing the `parsed_body` field populated.  I would expect some logging/error/warning message to help me understand why.  

## Actual Behavior
When using the envoy plugin: `package envoy.authz`, the only logs come if `content-type` is `application/json` or `application/grpc`.  If any other protocol, or omitted entirely, then nothing is logged even if the body is indeed json.  I needed to search in the code to determine why i wasn't seeing output.  

## Steps to Reproduce the Problem
1. send a request with no `content-type` header to OPA using the `package envoy.authz` package.  
2. examine logs and output.  No log will trigger (even in debug mode) and the `parsed_body` field will be empty

### Deployed image
```yaml
      - name: opa
        image: openpolicyagent/opa:latest-istio
        volumeMounts:
        - readOnly: true
          mountPath: /policy
          name: opa-policy
        args:
        - "run"
        - "--server"
        - "--addr=localhost:8181"
        - "--log-level=debug"
        - "--diagnostic-addr=0.0.0.0:8282"
        - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
        - "--set=plugins.envoy_ext_authz_grpc.query=data.envoy.authz.allow"
        - "--set=decision_logs.console=true"
        - "--ignore=.*"
        - "/policy/control-api.rego"
```

### Package used

```
# Use envoy package
package envoy.authz
```
