### ISSUE TITLE
Opa Bundle with aws s3 configuration help

### ISSUE THREAD

**Issue by vas-rus** [open-policy-agent/opa#3740]
Hi Team, 
I am new to opa server. 
I am working on using opa as authorizer for multiple policies and use case is that I upload multiple policies to s3 bucket and then each policy has his own link like /opa/example/allow or /opa/example1/approve. 
Now I want to use different requests coming to use this link along with data to check whether they are allowed for specific policy or not. 

I am little confused with config as I was going through opa docs. Can someone guide me for same. Following is config I am using and whenever I am hitting opa server it is giving blank response. I have taken this from some blog but not sure if it will work or not. 

config.yaml 
```services:
  bundle-s3:
    url: https://opa-testing1.s3.us-west-2.amazonaws.com/
    credentials:
      s3_signing:
        environment_credentials: {}
```  

inside this bucket I have a bundle with rego file as follow : 

```
package opa.examples

import input.user
import input.method

default allow = false

allow { user = "alice" }

allow {
    user = "bob"
    method = "GET"
}
```
opa server I am running using : opa run --server -c config.yaml

Request I am hitting is on : localhost:8181/v1/data/opa/example/allow 

Can someone help me how I can achieve my use case here and some blogs or examples will be very useful

**Comment by anderseknert** [comment]
Hi Vasu! I saw your question on StackOverflow too, but since that site doesn't lend itself too well to back-and-forth conversations, perhaps we can try and solve your issue here first, and then post the solution there for posterity.

Your config.yaml file looks incomplete. You'll need to at minimum define a _service_, then use that service in a _bundles_ configuration. From your example, this would look something like:

```yaml
services:
  bundle-s3:
    url: https://opa-testing1.s3.us-west-2.amazonaws.com/
    credentials:
      s3_signing:
        environment_credentials: {}

bundles:
  authz:
    service: bundle-s3
    resource: bundles/http/example/authz.tar.gz # change this to path of your bundle
```

Note that the `environment_credentials` option also requires the credentials to be found in environment variables, as per the [documentation](https://www.openpolicyagent.org/docs/latest/configuration/#using-static-environment-credentials).

If the above configuration doesn't work, make sure to check the OPA logs (preferable at debug level) as they should give you a good idea of where things go wrong.

**Comment by vas-rus** [comment]
Hi @anderseknert , 
Thanks for reply. 
However , Is resource field mandatory to point to bundle?  I want to have multiple bundles in this s3 and then depending on requirement call the api for specific bundle. If I point to specific bundle then I have to start one service for one bundle.

**Comment by anderseknert** [comment]
You can define as many bundles as you wish all referring to the same service.

**Comment by vas-rus** [comment]
@anderseknert  just to be sure according to you this config will work : 
```
bundles:
  authz:
    service: bundle-s3
    resource: bundles/http/example/authz.tar.gz
bundles:
  authz:
    service: bundle-s3
    resource: bundles/http/example/abc.tar.gz
```

Also , can a bundle contain more than one policy rego and data files ?

**Comment by anderseknert** [comment]
It would look like this:

```yaml
bundles:
  authz:
    service: bundle-s3
    resource: bundles/http/example/authz.tar.gz
  abc:
    service: bundle-s3
    resource: bundles/http/example/abc.tar.gz
```

> Also , can a bundle contain more than one policy rego and data files ?

Definitely! Make sure to check the [docs on bundles](https://www.openpolicyagent.org/docs/latest/management-bundles/) for how bundles are built.
