### ISSUE TITLE
Plugin manual trigger issue

### ISSUE THREAD

**Issue by manojnamodurai** [open-policy-agent/opa#3797]
## Issue Description
When `bundles[_].trigger` alone is set to `manual`  we are getting following error message from OPA while running: `error: config error: invalid configuration for bundle "bundle1": discovery has trigger mode periodic, bundle has manual`. 

Please note that we are not setting `discovery` plugin to `periodic` trigger in the config.yaml, it is a default setting.

## Expected Behavior
OPA should enable manual trigger for bundles plugin so that periodic download of bundles is disabled.

## Actual Behavior
OPA forces bundle and discovery plugins to have the same trigger mode.

## Steps to Reproduce the Problem

1. Set `bundles[_].trigger` to `manual` in config.yaml
2. Run OPA in server mode

* OPA version: 0.32.0
* config.yaml sample:
```
services:
  manager:
    url: http://localhost:8080/
    response_header_timeout_seconds: 5
labels:
  app: localhost:8181
  region: local
  environment: dev
bundles:
  bundle1:
    trigger: manual
    service: manager
    resource: /bundles/bundle1
    persist: true
status:
  service: manager
```
