### ISSUE TITLE
Compile errors in persisted bundles stop the server from starting

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#3837]
When a bundle that was previously persisted is loaded into OPA, compile errors halt the server completely. While OPA does not persist broken bundles, some errors could be due to dependencies to other data not yet loaded into OPA when the persisted bundle is loaded. An example configuration that shows this might look like this:

```yaml
services:
    nginx:
        url: http://localhost

bundles:
    a:
        service: nginx
        resource: x.tar.gz
        persist: true

    b:
        service: nginx
        resource: y.tar.gz
```

In the above example - if bundle `a` (which is persisted) **has a dependency to a function** in bundle `b` (which is not persisted) then OPA will load bundle `a` and exit when it encounters compilation errors. 

## Expected behavior 
OPA would continue to run (albeit temporarily in a non-ready state) and fetch the other bundles from configuration. In other words, errors in persisted bundles should be treated the same way as errors in bundles sourced elsewhere.

## Steps to reproduce
Start OPA with above config. Stop OPA to persist bundle `a`. Remove bundle `b` from remote server. Start OPA.
