### ISSUE TITLE
Why is my policy evaluation result always true?

### ISSUE THREAD

**Issue by cyclinder** [open-policy-agent/opa#3896]
i wrote a policy about prevents Kubernetes Pods from using containers from untrusted image 

```
package kubernetes.validating.images

deny[msg] {
    some i
    input.request.kind.kind == "Pod"
    image := input.request.object.spec.containers[i].image
    not startswith(image, "hooli.com/")
    msg := sprintf("Image '%v' comes from untrusted registry", [image])
}
```
and i then created a pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
```

The expected result is that the request is rejected，but it returns allowed,I don't know what went wrong
# registries

## Expected Behavior
Pod creation requests will be rejected

## Actual Behavior

the requests is allowed
## Steps to Reproduce the Problem

i followed [https://www.openpolicyagent.org/docs/v0.32.1/kubernetes-tutorial/](https://www.openpolicyagent.org/docs/v0.32.1/kubernetes-tutorial/)

webhook-configuration.yaml :
```
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: opa-validating-webhook
webhooks:
  - name: validating-webhook.openpolicyagent.org
    namespaceSelector:
      matchExpressions:
      - key: openpolicyagent.org/webhook
        operator: NotIn
        values:
        - ignore
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    clientConfig:
      caBundle: ****
      service:
        namespace: opa
        name: opa
    admissionReviewVersions: ["v1beta1","v1"]
    sideEffects: None
```
admission-controller.yaml :
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opa-viewer
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:opa
  apiGroup: rbac.authorization.k8s.io
---
# Define role for OPA/kube-mgmt to update configmaps with policy status.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: opa
  name: configmap-modifier
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "patch"]
---
# Grant OPA/kube-mgmt role defined above.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: opa
  name: opa-configmap-modifier
roleRef:
  kind: Role
  name: configmap-modifier
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:opa
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: opa
  namespace: opa
spec:
  selector:
    app: opa
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opa
  namespace: opa
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      containers:
        # WARNING: OPA is NOT running with an authorization policy configured. This
        # means that clients can read and write policies in OPA. If you are
        # deploying OPA in an insecure environment, be sure to configure
        # authentication and authorization on the daemon. See the Security page for
        # details: https://www.openpolicyagent.org/docs/security.html.
        - name: opa
          image: openpolicyagent/opa:0.32.1-rootless
          args:
            - "run"
            - "--server"
            - "--tls-cert-file=/certs/tls.crt"
            - "--tls-private-key-file=/certs/tls.key"
            - "--addr=0.0.0.0:8443"
            - "--addr=http://127.0.0.1:8181"
            - "--log-format=json-pretty"
            - "--set=decision_logs.console=true"
          volumeMounts:
            - readOnly: true
              mountPath: /certs
              name: opa-server
          readinessProbe:
            httpGet:
              path: /health?plugins&bundle
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 3
            periodSeconds: 5
        - name: kube-mgmt
          image: openpolicyagent/kube-mgmt:0.11
          args:
            - "--replicate-cluster=v1/namespaces"
            - "--replicate=appv1/deployments"
            - "--replicate=v1/pods"
      volumes:
        - name: opa-server
          secret:
            secretName: opa-server
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-default-system-main
  namespace: opa
data:
  main: |
    package system

    import data.kubernetes.admission

    main = {
      "apiVersion": "admission.k8s.io/v1beta1",
      "kind": "AdmissionReview",
      "response": response,
    }

    default uid = ""

    uid = input.request.uid

    response = {
        "allowed": false,
        "uid": uid,
        "status": {
            "message": reason,
        },
    } {
        reason = concat(", ", admission.deny)
        reason != ""
    }
    else = {"allowed": true, "uid": uid}
```

decision-log from pod "opa":
```
{
  "decision_id": "3b2cfc81-edef-470c-befe-87d2c23b4b0c",
  "input": {
    "apiVersion": "admission.k8s.io/v1beta1",
    "kind": "AdmissionReview",
    "request": {
      "dryRun": false,
      "kind": {
        "group": "",
        "kind": "Pod",
        "version": "v1"
      },
      "name": "busybox",
      "namespace": "default",
      "object": {
        "apiVersion": "v1",
        "kind": "Pod",
        "metadata": {
          "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Pod\",\"metadata\":{\"annotations\":{},\"name\":\"busybox\",\"namespace\":\"default\"},\"spec\":{\"containers\":[{\"command\":[\"sleep\",\"3600\"],\"image\":\"busybox\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"busybox\"}]}}\n"
          },
          "creationTimestamp": "2021-10-18T06:33:59Z",
          "managedFields": [
            {
              "apiVersion": "v1",
              "fieldsType": "FieldsV1",
              "fieldsV1": {
                "f:metadata": {
                  "f:annotations": {
                    ".": {},
                    "f:kubectl.kubernetes.io/last-applied-configuration": {}
                  }
                },
                "f:spec": {
                  "f:containers": {
                    "k:{\"name\":\"busybox\"}": {
                      ".": {},
                      "f:command": {},
                      "f:image": {},
                      "f:imagePullPolicy": {},
                      "f:name": {},
                      "f:resources": {},
                      "f:terminationMessagePath": {},
                      "f:terminationMessagePolicy": {}
                    }
                  },
                  "f:dnsPolicy": {},
                  "f:enableServiceLinks": {},
                  "f:restartPolicy": {},
                  "f:schedulerName": {},
                  "f:securityContext": {},
                  "f:terminationGracePeriodSeconds": {}
                }
              },
              "manager": "kubectl-client-side-apply",
              "operation": "Update",
              "time": "2021-10-18T06:33:59Z"
            }
          ],
          "name": "busybox",
          "namespace": "default",
          "uid": "cde963cf-b926-4bab-95cd-231fbf6b29a0"
        },
        "spec": {
          "containers": [
            {
              "command": [
                "sleep",
                "3600"
              ],
              "image": "busybox",
              "imagePullPolicy": "IfNotPresent",
              "name": "busybox",
              "resources": {},
              "terminationMessagePath": "/dev/termination-log",
              "terminationMessagePolicy": "File",
              "volumeMounts": [
                {
                  "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                  "name": "kube-api-access-5g22m",
                  "readOnly": true
                }
              ]
            }
          ],
          "dnsPolicy": "ClusterFirst",
          "enableServiceLinks": true,
          "preemptionPolicy": "PreemptLowerPriority",
          "priority": 0,
          "restartPolicy": "Always",
          "schedulerName": "default-scheduler",
          "securityContext": {},
          "serviceAccount": "default",
          "serviceAccountName": "default",
          "terminationGracePeriodSeconds": 30,
          "tolerations": [
            {
              "effect": "NoExecute",
              "key": "node.kubernetes.io/not-ready",
              "operator": "Exists",
              "tolerationSeconds": 300
            },
            {
              "effect": "NoExecute",
              "key": "node.kubernetes.io/unreachable",
              "operator": "Exists",
              "tolerationSeconds": 300
            }
          ],
          "volumes": [
            {
              "name": "kube-api-access-5g22m",
              "projected": {
                "sources": [
                  {
                    "serviceAccountToken": {
                      "expirationSeconds": 3607,
                      "path": "token"
                    }
                  },
                  {
                    "configMap": {
                      "items": [
                        {
                          "key": "ca.crt",
                          "path": "ca.crt"
                        }
                      ],
                      "name": "kube-root-ca.crt"
                    }
                  },
                  {
                    "downwardAPI": {
                      "items": [
                        {
                          "fieldRef": {
                            "apiVersion": "v1",
                            "fieldPath": "metadata.namespace"
                          },
                          "path": "namespace"
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        },
        "status": {
          "phase": "Pending",
          "qosClass": "BestEffort"
        }
      },
      "oldObject": null,
      "operation": "CREATE",
      "options": {
        "apiVersion": "meta.k8s.io/v1",
        "fieldManager": "kubectl-client-side-apply",
        "kind": "CreateOptions"
      },
      "requestKind": {
        "group": "",
        "kind": "Pod",
        "version": "v1"
      },
      "requestResource": {
        "group": "",
        "resource": "pods",
        "version": "v1"
      },
      "resource": {
        "group": "",
        "resource": "pods",
        "version": "v1"
      },
      "uid": "c4093c19-695f-4c1e-86b9-f065ed156d61",
      "userInfo": {
        "groups": [
          "system:masters",
          "system:authenticated"
        ],
        "username": "minikube-user"
      }
    }
  },
  "labels": {
    "id": "4a4dd1bf-0d69-4b73-9c14-d8cfb561cfe5",
    "version": "0.32.1"
  },
  "level": "info",
  "metrics": {
    "counter_server_query_cache_hit": 0,
    "timer_rego_external_resolve_ns": 9800,
    "timer_rego_query_compile_ns": 546000,
    "timer_rego_query_eval_ns": 1146000,
    "timer_rego_query_parse_ns": 30700,
    "timer_server_handler_ns": 3664800
  },
  "msg": "Decision Log",
  "path": "system/main",
  "requested_by": "172.17.0.1:30209",
  "result": {
    "apiVersion": "admission.k8s.io/v1beta1",
    "kind": "AdmissionReview",
    "response": {
      "allowed": true,
      "uid": "c4093c19-695f-4c1e-86b9-f065ed156d61"
    }
  },
  "time": "2021-10-18T06:33:59Z",
  "timestamp": "2021-10-18T06:33:59.2570271Z",
  "type": "openpolicyagent.org/decision_logs"
}
```

Can anyone tell me where the problem is ？

## Additional Info
clusterType: minikube
clusterInfo:
```
root@root ~/opa/deploy$ kubectl version -o yaml
clientVersion:
  buildDate: "2021-08-11T18:16:05Z"
  compiler: gc
  gitCommit: 3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae
  gitTreeState: clean
  gitVersion: v1.21.4
  goVersion: go1.16.7
  major: "1"
  minor: "21"
  platform: darwin/amd64
serverVersion:
  buildDate: "2021-08-19T15:39:34Z"
  compiler: gc
  gitCommit: 632ed300f2c34f6d6d15ca4cef3d3c7073412212
  gitTreeState: clean
  gitVersion: v1.22.1
  goVersion: go1.16.7
  major: "1"
  minor: "22"
  platform: linux/amd64
```
