### ISSUE TITLE
Compile API failed for opa-envoy

### ISSUE THREAD

**Issue by 27149chen** [open-policy-agent/opa#4032]
## Short description 

opa version: opa:0.34.2-envoy-1
problem: Trying to run "POST /v1/compile", but the request was stuck. After a long time (100+s), the opa pod is killed because of OOM.

## Steps To Reproduce
1. Send the following request:
```
curl -X POST -H 'Content-Type: application/json' -i 'http://xxxx:8181/v1/compile?pretty' --data '{
  "query": "data.rbac.allow"
}'
```

## Expected behavior

The server should return right response

## Additional context

the opa pod is killed because of OOM and there is no error messages.
BTW: I run "opa run -s" locally with same config, everyting is fine.

**Comment by srenatus** [comment]
What have you been trying to do here? I'm not sure I see how the opa-envoy-plugin and the compile API go together (but what you describe should nonetheless be possible). Just trying to get a fuller picture here.

**Comment by 27149chen** [comment]
@srenatus , Sorry I forgot to mention that, we also use the http service exposed by the opa-envoy-plugin to do some filtering like returning only the allowed items in a list.
After reading this article: https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4, we what to do something similiar, so I'm investigating the compile API.

**Comment by srenatus** [comment]
Ah thank you! When you play with PE in the REPL or using `opa eval`, with the same data, do you see the same effect?

I'd advise against starting out against the Compile API to explore PE and data filtering. In the end, you'll probably use it, but it's not step one.

In the repl you can use `unknown input` to trigger PE mode. For `opa eval`, a good CLI invocation would be
```
opa eval --format source --partial --data my.rego data.some.rule
```

**Comment by 27149chen** [comment]
everything is fine in the REPL. I just want to make sure if it works in opa-envoy-plugin.

**Comment by srenatus** [comment]
Ah I see. Can you run the same with opa-envoy-plugin locally? Just to rule out that it has anything to do with k8s and its OPA instance's resource limits.

**Comment by 27149chen** [comment]
tried to run opa-envoy-plugin locally, the response is returned immediately. but if I run it in pod (2c4g), the pod oom again

**Comment by srenatus** [comment]
Hrm that's something 😅 I guess your desktop exceeds 2c4g by far, perhaps you could try giving opa-envoy-plugin more resources?

**Comment by 27149chen** [comment]
limit the local resource to 1c2g, returned immediately again

**Comment by srenatus** [comment]
Interesting. Well, I suppose I can only guess here -- what else could be different in your pod?

**Comment by 27149chen** [comment]
I don't know. I use same config, same run params and same bundle server. And I test the Data API, it works well.

**Comment by srenatus** [comment]
Is there any other traffic maybe? Are envoy requests being processed at the same time?

**Comment by 27149chen** [comment]
traffic is low, it is just a test service, from opa log, I can tell it is the only one request when I send the Compile request

**Comment by srenatus** [comment]
I'm afraid I'm out of ideas. Maybe @ashutosh-narkar has some?

**Comment by ashutosh-narkar** [comment]
@27149chen running the `opa-envoy-plugin` locally returns the response. You seem to have confirmed this. Can you share your manifest and how you're exposing the service in your k8s setup ? Have you tried turning on console logging (`--set=decision_logs.console=true`) and checked if `opa-envoy-plugin` gets any logs ?

**Comment by 27149chen** [comment]
log is enabled, here is the last log before crashing:
```
{"client_addr":"127.0.0.1:53622","level":"info","msg":"Received request.","req_id":5,"req_method":"POST","req_path":"/v1/compile","time":"2021-11-18T13:09:32Z"}
```

**Comment by 27149chen** [comment]
Almost the same as the example: https://github.com/open-policy-agent/opa-envoy-plugin/blob/main/examples/gloo-edge/opa.yaml

deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: opa
  name: opa
  namespace: nga
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: opa
  template:
    metadata:
      labels:
        app.kubernetes.io/component: opa
    spec:
      containers:
      - args:
        - run
        - --server
        - --config-file=/config/config.yaml
        - --addr=0.0.0.0:8181
        - --set=plugins.envoy_ext_authz_grpc.addr=0.0.0.0:9191
        - --set=plugins.envoy_ext_authz_grpc.query=data.rbac.response
        - --set=decision_logs.console=true
        - --ignore=.*
        image: openpolicyagent/opa:0.34.2-envoy-1
        imagePullPolicy: IfNotPresent
        name: opa
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        volumeMounts:
        - mountPath: /config
          name: opa-envoy-config
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: opa-envoy-config
        name: opa-envoy-config
```

service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: opa
  name: opa
  namespace: nga
spec:
  ports:
  - name: grpc
    port: 9191
    protocol: TCP
    targetPort: 9191
  - name: tcp
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app.kubernetes.io/component: opa
  type: ClusterIP
```
