### ISSUE TITLE
opa envoy is unable to process the request on payload size greater than 4MB

### ISSUE THREAD

**Issue by keshavprasadms** [open-policy-agent/opa#4187]
Hi there,

I am facing an issue while using the opa-envoy plugin wherein I cannot upload a file greater than 4MB. We are using OPA to do some API checks and some APIs have the option of accepting binary files like .mp3, .ogg etc. I beleive I will get a similar issue if I try to upload a json file > 4MB.

Initially I was getting 413 (payload too large) from envoy for files > 1 MB which got resolved after using `per_connection_buffer_limit_bytes: 62914560`

OPA version: 0.34.2 (Also tried with 0.35.0)

I have set 65MB as the max payload size in Envoy
```
        per_connection_buffer_limit_bytes: 62914560
        filter_chains:
        - filters:
              http_filters:
              - name: envoy.filters.http.ext_authz
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                  transport_api_version: V3
                  with_request_body:
                    max_request_bytes: 62914560
                    pack_as_bytes: true
                    allow_partial_message: true
                  failure_mode_allow: false
                  grpc_service:
                    envoy_grpc:
                      cluster_name: ext_authz
                    timeout: 5s

      clusters:
      - name: ext_authz
        connect_timeout: 30s
        per_connection_buffer_limit_bytes: 62914560
        type: static
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              http2_protocol_options: {}
        load_assignment:
          cluster_name: ext_authz
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 9191
```
I came across this comment - https://github.com/open-policy-agent/opa/issues/2977#issuecomment-739920511

Envoy does not even connect to OPA and just returns a 403.
```
[2022-01-06T09:37:55.519Z] "POST /content/v3/upload/do_31344685567759974412 HTTP/1.1" 403 UAEX 5025734 0 12 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "5f03c48539cec93f3da07dd60140a677" "content-service:9000" "-"
```
The upload of files > 4M works if I set `failure_mode_allow: true` on envoy. Which means, there is some trouble in establishing the connection on such payloads from envoy -> opa.

Do you guys have any suggestions on how to get around this 4MB limit or any other thoughts on how I can get this working?
