### ISSUE TITLE
Issues when connecting to Azure managed identity

### ISSUE THREAD

**Issue by superff** [open-policy-agent/opa#4206]
## Short description 

Hello

I am encountering this 'issue' when using azure managed identity to access the storage account, the error is failed on auth plugin

{"level":"error","msg":"Bundle load failed: request failed: invalid character 'i' in literal false (expecting 'l')","name":"authz","plugin":"bundle","time":"2022-01-10T23:39:05Z"}

{"level":"error","msg":"Bundle load failed: request failed: Get \"http://169.254.169.254/metadata/identity/oauth2/token???": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","name":"authz","plugin":"bundle","time":"2022-01-10T23:29:53Z"}

## Steps To Reproduce

1. in Config map
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: '#{APP_NAME}#'
data:
  config.yaml: |
    services:
      policy:
        url: ${POLICY_URL}
        response_header_timeout_seconds: 60
        headers:
          # x-ms-version and x-ms-blob-type are required! Do not remove!!
          x-ms-version: 2020-04-08
          x-ms-blob-type: BlockBlob
          Metadata: 'true'
        credentials:
          # https://www.openpolicyagent.org/docs/latest/configuration/#azure-managed-identities-token
          azure_managed_identity:
            endpoint: http://169.254.169.254/metadata/identity/oauth2/token
            api_version: 2018-02-01
            resource: https://storage.azure.com

    bundles:
      authz:
        service: policy
        resource: opa-bundles/bundle-latest.tar.gz
        polling:
          # Fetch bundles roughly every minute
          min_delay_seconds: 50
          max_delay_seconds: 70

    decision_logs:
      service: policy
      console: true

```
