### ISSUE TITLE
Load bundle from failover service

### ISSUE THREAD

**Issue by rmetcalf9** [open-policy-agent/opa#4397]
## What part of OPA would you like to see improved?
The OPA config file needs an option to load a bundle from multiple services.
This will allow us to configure it to load from an S3 bucket, but if that bucket is down to revert to a backup service for getting that bundle. Che config could look something like:

```
services:
  s3:
    url: https://my-bundle-bucket-a.s3.eu-west-1.amazonaws.com
    credentials:
      s3_signing:
        metadata_credentials:
          aws_region: eu-west-1
  s3b:
    url: https://my-bundle-bucket-b.s3.eu-west-1.amazonaws.com
    credentials:
      s3_signing:
        metadata_credentials:
          aws_region: eu-west-1

bundles:
  authz:
    service: s3, s3b
    resource: live-policy-bundle.tar.gz
    persist: true
    polling:
      min_delay_seconds: 30
      max_delay_seconds: 60
```

Here the service entry in the bundle has both s3 and s3b which would result in the agent getting the bundle from s3b when s3 is not available.

## Additional Context
I discussed the use case for this [here](https://github.com/open-policy-agent/community/discussions/139])
