### ISSUE TITLE
opa-envoy-plugin: add support for `OkHttpResponse.response_headers_to_add`

### ISSUE THREAD

**Issue by pvsone** [open-policy-agent/opa#4417]
Envoy has recently enhanced the capabilities of an external authorization service to add response headers to an Ok response, through the `response_headers_to_add` field [1].  

It would be useful for the OPA envoy plugin to support this, so that the policy could contribute header fields/values with an Ok response.  In the current state headers can only be added to an Ok "request" or a Denied response. 

[1] https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto#service-auth-v3-okhttpresponse

**Comment by Cerfoglg** [comment]
This feature would be nice to have for us as well, as one project we are working on could use returning custom headers on an OK response.

**Comment by chicco785** [comment]
do you know when this feature will be officially released? many thanks!

**Comment by ashutosh-narkar** [comment]
It's already released! See https://github.com/open-policy-agent/opa-envoy-plugin/releases/tag/v0.38.1-envoy-3.

**Comment by chicco785** [comment]
mmm, is there a special trick to make the functionality work? also with the new version we get the custom header only in case of 4xx response.

**Comment by chicco785** [comment]
sorted out, issue was with envoy image ;)

**Comment by salrashid123** [comment]
@chicco785 , @ashutosh-narkar  is it possile to post a snippet of the rego and the envoy version you're using?

i've been trying to get opa+envoy to return a header:

in my caase, i'm using a standalone envoy  (not istio or gloo) which enlists an external authz server which is opa

envoy -> opa
```yaml
                http_filters:
                - name: envoy.filters.http.ext_authz
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                    transport_api_version: V3                    
                    grpc_service:
                      google_grpc:
                        target_uri: 127.0.0.1:9191
                        stat_prefix: ext_authz
                      timeout: 3s
```

the opa rego i have makes an external call like this to retrieve some data and inject it back to upstream (upstream of envoy, that is)

```
external_data = {"status_code": status_code, "body": body} {
  r := http.send({"method": "POST", "url": "http://server.yourdomain.com:8443/authz", "body": "alice@domain.com"})
  status_code := r.status_code 
  body := r.body
}

allow {
    is_in_security_group
    action_allowed    
}

headers["x-ext-auth-allow"] = "yes"
headers["x-validated-by"] = "security-checkpoint"
request_headers_to_remove = ["xfoo", "another-auth-header"]
request_headers_to_add["x-google-groups"] = external_data.body["groups"] 

is_in_security_group {
  external_data.status_code == 200
  some "securitygroup1@esodemoapp2.com" in external_data.body["groups"] 
}

action_allowed {
  http_request.method == "GET"
  glob.match("/get*", [], http_request.path)
}

```


---

no matter what i tried, the envoy sees opa return an empty `CheckResponse` object back to envoy

```log
[2022-05-18 08:51:43.879][345386][trace][ext_authz] [source/extensions/filters/common/ext_authz/ext_authz_grpc_impl.cc:48] Received CheckResponse: status {
}
```

I wroteup a small [envoy_external_authz](https://github.com/salrashid123/envoy_external_authz) and i can confirm that when envoy is run with debug mode, it should see that resposne populated like this

```log
[2022-05-18 08:56:51.331][347054][trace][ext_authz] [source/extensions/filters/common/ext_authz/ext_authz_grpc_impl.cc:48] Received CheckResponse: status {
}
ok_response {
  headers {
    header {
      key: "x-custom-header-from-authz"
      value: "some value"
    }
  }
}

```

---

am i just....not defining the rego correctly to emit data back to envoy?


https://play.openpolicyagent.org/p/4EQ4sN7GNG


---

i tried both opa docker ` openpolicyagent/opa:0.38.0-envoy-3-static`

```
$ ./opa_envoy_linux_amd64 version
Version: 0.38.1-envoy-3
Build Commit: 2977de0d
Build Timestamp: 2022-03-23T23:17:46Z
Build Hostname: 0d28ba8a89c8
Go Version: go1.17.7
Platform: linux/amd64
WebAssembly: unavailable


envoy --version
  /apps/envoy/envoy  version: dc7f46eb44e54d5646301aa5ab4ba01f662fdf75/1.21.2/Clean/RELEASE/BoringSSL
```
