### ISSUE TITLE
Add OCI support

### ISSUE THREAD

**Issue by carabasdaniel** [open-policy-agent/opa#4518]
## What part of OPA would you like to see improved?

We would like OPA to be able to consume bundles from an OCI registry. This integration will allow us to take advantage of the richness of the OCI ecosystem including but not limited to image signing, versioning,  caching, layering, etc. 

## Describe the ideal solution

Ideally once this is implemented a user could use a configuration similar to the example below to consume a bundle from an OCI registry.

Example: 
```yaml
services:
  github-registry:
    url: https://ghcr.io
    type: oci
    credentials:
      username: alice
      password: secret

bundles:
  authz:
    service: github-registry
    resource: open-policy-agent/my-bundle:1.0.1
    persist: true
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120

# The local OCI store would be persisted to /var/opa/oci
persistence_directory: /var/opa
```

## Additional Context

To implement this we thought we should create a downloader interface and implement an `OCIDownloader` - `download.NewOCI(...)`. The current downloader can remain as the default http downloader. 

To drive the implementation of the new OCIDownloader we would like to use  [ORAS](https://github.com/oras-project/oras-go) as it would offer higher level constructs that are easier to implement with.

For additional details please consult the following [document](https://docs.google.com/document/d/1t-pfReTyLp0B_BEoubllOGit0HADoTOrL4ZkfbENXac/edit?usp=sharing) that was presented in the OPA community call.
