### ISSUE TITLE
Filter outbound OPA decision logs at OPA level

### ISSUE THREAD

**Issue by dolevf** [open-policy-agent/opa#4572]
hey OPA mates,

On high volume OPA instances, a lot of decisions are generated, and logging can become harder as a result. Often, it's required to only grab specific events. 

I think it will be useful to have a filtering capability on outgoing decision logging instead of having an external service dedicated for this. It also helps saving costs on platforms such as SaaS logging systems. 

AFAIK, this is not possible today without a remote logger filtering the data, perhaps maybe OPA could introduce a filtering layer before decisions are sent over the wire? something like this:

```
decision_logs:
  service: siem
  resource: /logs
  console: true
  filter: 
     path: input/service_name # JSON path
     match_by: regex
     matches: /^(backup-service|file-service)$/
  reporting:
    min_delay_seconds: 30
    max_delay_seconds: 90
```
