### ISSUE TITLE
Get policy by package name via REST API

### ISSUE THREAD

**Issue by NitroCao** [open-policy-agent/opa#4647]
## What part of OPA would you like to see improved?

REST API.

## Describe the ideal solution

For example, we have a rego file called `hello.rego`:
```
package greeting

default deny = true

deny {
    input.user == "nitro"
}
```
Then run an OPA server with `opa run -s -b .`. For now we can get the policy only if we know the policy path:
```
curl http://localhost:8181/v1/policies/hello.rego

{"result":{"id":"hello.rego","raw":"package greeting\n\ndefault deny = true\n\ndeny {\n\tinput.user == \"nitro\"\n}\n","ast":{"package":{"path":[{"type":"var","value":"data"},{"type":"string","value":"greeting"}]},"rules":[{"default":true,"head":{"name":"deny","value":{"type":"boolean","value":true}},"body":[{"terms":{"type":"boolean","value":true},"index":0}]},{"head":{"name":"deny","value":{"type":"boolean","value":true}},"body":[{"terms":[{"type":"ref","value":[{"type":"var","value":"eq"}]},{"type":"ref","value":[{"type":"var","value":"input"},{"type":"string","value":"user"}]},{"type":"string","value":"nitro"}],"index":0}]}]}}}
```
But the package name is more stable than the policy path. So hope that we can get the policy by the package name:
```
curl http://localhost:8181/v1/policies/greeting?package=true

{"result":{"id":"hello.rego","raw":"package greeting\n\ndefault deny = true\n\ndeny {\n\tinput.user == \"nitro\"\n}\n","ast":{"package":{"path":[{"type":"var","value":"data"},{"type":"string","value":"greeting"}]},"rules":[{"default":true,"head":{"name":"deny","value":{"type":"boolean","value":true}},"body":[{"terms":{"type":"boolean","value":true},"index":0}]},{"head":{"name":"deny","value":{"type":"boolean","value":true}},"body":[{"terms":[{"type":"ref","value":[{"type":"var","value":"eq"}]},{"type":"ref","value":[{"type":"var","value":"input"},{"type":"string","value":"user"}]},{"type":"string","value":"nitro"}],"index":0}]}]}}}
```

## Describe a "Good Enough" solution

I modified [v1PoliciesGet()](https://github.com/open-policy-agent/opa/blob/c023bb6ebe843162ab49ff1716876f517806e47c/server/server.go#L1898) method to achieve this feature. Does someone have any suggestion on this feature?
``` diff
diff --git a/server/server.go b/server/server.go
index e52bc40d..d96a33dd 100644
--- a/server/server.go
+++ b/server/server.go
@@ -1906,6 +1906,7 @@ func (s *Server) v1PoliciesGet(w http.ResponseWriter, r *http.Request) {
        }

        pretty := getBoolParam(r.URL, types.ParamPrettyV1, true)
+       isPackage := getBoolParam(r.URL, "package", false)

        txn, err := s.store.NewTransaction(ctx)
        if err != nil {
@@ -1915,19 +1916,39 @@ func (s *Server) v1PoliciesGet(w http.ResponseWriter, r *http.Request) {

        defer s.store.Abort(ctx, txn)

-       bs, err := s.store.GetPolicy(ctx, txn, path)
+       var bs []byte
+       var module *ast.Module
+       policyPath := path
+       c := s.getCompiler()
+
+       if isPackage {
+               dataPath := fmt.Sprintf("data.%s", path)
+               for p, m := range c.Modules {
+                       if m.Package.Path.String() == dataPath {
+                               module = m
+                               policyPath = p
+                               break
+                       }
+               }
+               if module == nil {
+                       writer.ErrorAuto(w, fmt.Errorf("non-existing package %s", path))
+                       return
+               }
+       } else {
+               module = c.Modules[path]
+       }
+
+       bs, err = s.store.GetPolicy(ctx, txn, policyPath)
        if err != nil {
                writer.ErrorAuto(w, err)
                return
        }

-       c := s.getCompiler()
-
        response := types.PolicyGetResponseV1{
                Result: types.PolicyV1{
-                       ID:  path,
+                       ID:  policyPath,
                        Raw: string(bs),
-                       AST: c.Modules[path],
+                       AST: module,
                },
        }
```

**Comment by anderseknert** [comment]
Hi @NitroCao 👋 And thanks for filing this. Could you elaborate some on what you're trying to accomplish? In general, I don't think the ID of policies should matter much once they've been loaded into OPA.

As for the implementation, I'd expect the URL to get all policies from the `greeting` package to look something like this:
```
http://localhost:8181/v1/policies?package=greeting
```
Should this include any sub-packages as well? I.e `greeting.hello`, `greeting.goodbye` and so on?

If you'd want to accomplish something like this today, you could simply list all policies, e.g.

```
http://localhost:8181/v1/policies
```
and then filter the result from that based on the first line starting with `package`... but yeah, not terribly elegant.

**Comment by NitroCao** [comment]
@anderseknert  Thanks for your reply.

>  In general, I don't think the ID of policies should matter much once they've been loaded into OPA.

But the ID depends on the policy path. From the example above, the initial directory layout inside a bundle is:
```
.
├── .manifest
└── hello.rego

0 directories, 2 files
```
At this time, the ID of the policy is `hello.rego`.

In the future, I changed the directory layout to the following because of some reason:
```
.
├── .manifest
└── hello
    └── hello.rego

1 directory, 2 files
```
Now, the ID of the policy becomes `hello/hello.rego`.


For a specific scenario, I want to create a constraint template of gatekeeper, and the content of the template is like the following:
``` yaml
kind: ConstraintTemplate
apiVersion: templates.gatekeeper.sh/v1
metadata:
  name: k8sdisallowedhostpathvolumes
spec:
  crd:
    spec:
      names:
        kind: K8sDisallowedHostpathVolumes
      validation:
        openAPIV3Schema:
          type: object
          properties:
            exemptApps:
              type: array
              items:
                type: object
                properties:
                  namespace:
                    type: string
                  paths:
                    type: array
                    items:
                      type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: kubernetes/podsecuritypolicy/hostpath-volumes-mounted.rego
      libs:
        - lib/kubernetes.rego
        - lib/general.rego
```
Note the `targets[].rego` and `targets[].libs` fields, in order to better organize and manage Rego rules, I'll replace the two fields with corresponding content by requesting OPA REST API before creating the template. The rules are loaded into OPA as a bundle.

In future, we may change the directory layout of the bundle for any reason. Then, we also have to modify the two fields `targets[].rego` and `targets[].libs`. 
But people rarely change the package names. If we use package names here instead of policy paths, we don't need to modify the template anymore no matter how we change the directory layout of the bundle, as long as we don't change package names. This is what I said "the package name is more stable than the policy path".


> Should this include any sub-packages as well? I.e greeting.hello, greeting.goodbye and so on?

The feature to be added is just to get a specific package. Given that we only have the following two policies:
```
# hello_english.rego

package greeting.hello.english

default deny = true

deny {
    input.name == "Jane"
}
```
```
# hello_chinese.rego

package greeting.hello.chinese

default deny = true

deny {
    input.name == "Jane"
}
```

In this situation, `/v1/policies/greeting.hello.english?package=true` and `/v1/policies/greeting.hello.chinese?package=true` both return 200,  but `/v1/policies/greeting.hello` returns 404 because of no such package.
