### ISSUE TITLE
OCI auth: Pulling OCI policybundles from Amazon ECR private repos fails with 401 Unauthorized

### ISSUE THREAD

**Issue by bleggett** [open-policy-agent/opa#4680]
## Short description 

OCI registry auth is not working in OPA's downloader with Amazon ECR, even though it works with `policy` CLI tool (and `ghcr.io`) as documented.

- I've got a private OCI registry created in Amazon ECR.
- I can `login`/`push`/`pull` to this private registry just fine with the `policy` CLI tool as [described here](https://github.com/open-policy-agent/opa/blob/v0.40.0/docs/devel/OCI.md), as one would expect:

```
aws ecr get-login-password --region us-east-2 | policy login --username AWS --password-stdin --server="<ACCTID>.dkr.ecr.us-east-2.amazonaws.com"
```

I can then push a policy bundle as an OCI artifact with auth:

```
policy push <ACCTID>.dkr.ecr.us-east-2.amazonaws.com/<policy>:0.0.1
```

Authed pulling works too:

```
policy pull <ACCTID>.dkr.ecr.us-east-2.amazonaws.com/<policy>:0.0.1
```

But when I go to put this into an OPA `services` config so it can actually be fetched, no matter what I do, I get `401 unauthorized` errors and the policy image can't be pulled:

Using `Bearer` configs doesn't work (I wouldn't expect it to tho? Should be `basic` Authorization header type as per `policy` CLI auth code).
```
services:
  ecr-registry:
    url: https://<ACCTID>.dkr.ecr.us-east-2.amazonaws.com
    type: oci
    credentials:
      bearer:
        token: <token from "aws ecr get-login-password">

bundles:
  authz:
    service: ecr-registry
    resource: <ACCTID>.dkr.ecr.us-east-2.amazonaws.com/<policy>:0.0.1
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120

```

Using `Basic` auth config (generating a token from the `AWS` username and the above token joined with a `:` as per normal HTTP basic auth) **also** doesn't work, and, AFAIK, this should work, just like it does for the `policy` tool?

```
    credentials:
      bearer:
        token: "basic auth header token created from <username>:<token>"
        scheme: basic

```
I'm out of ideas on how to auth, since that should work, as far as I can tell from reading the downloader auth code?

No matter which of those I try, I get:
```
INFO[0000] Starting bundle loader.                       name=authz plugin=bundle
DEBU[0000] OCI - Download starting.                     
ERRO[0000] Bundle load failed: failed to pull xxxx.dkr.ecr.us-east-2.amazonaws.com/policybundle:0.0.1: download for 'xxx.dkr.ecr.us-east-2.amazonaws.com/policybundle:0.0.1' failed: pulling from host xxx.dkr.ecr.us-east-2.amazonaws.com failed with status code [manifests 0.0.1]: 401 Unauthorized  name=authz plugin=bundleDEBU[0000] OCI - Waiting 0s before next download/retry. 
DEBU[0000] OCI - Download starting.                     
```

and so on.

## Expected behavior
I should be able to pull OCI artifacts from OCI repositories that require authentication.

Examples:

* OPA version: 0.40

**Comment by bleggett** [comment]
Should note that `ghcr.io` auth works fine with just

```
services:
  ghcr-registry:
    url: https://ghcr.io
    type: oci
    credentials:
      bearer:
        token: "${CR_PAT}"

bundles:
  authz:
    service: ghcr-registry
    resource: ghcr.io/bleggett/policybundle:0.0.1
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120
```

but ECR doesn't seem happy with the same approach, for some reason.
