### ISSUE TITLE
disk storage: symlink logic fails if using relative directories

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#4869]
With an OPA config like

```yaml
services:
  bundles:
    url: http://127.0.0.1:8000
bundles:
  perms:
    service: bundles
    resource: simple.tar.gz
storage:
  disk:
    directory: _tmp_simple
    auto_create: true
```

the server would create a symlink of
```
active -> _tmp_simple/backupXXXX
```
after successful bundle activation.

**On restart**, it would try to resolve `_tmp_simple/active`, and fail to find `_tmp_simple/_tmp_simple/active`:

```
error: initialize disk store: storage_internal_error: lstat _tmp_simple/_tmp_simple: no such file or directory
```

A **workaround** is to configure disk storage with _absolute paths_ instead; the symlink will then be properly created.

Once the symlink is wrong, however, it needs to manually be fixed. In the `_tmp_simple` example above, that would be
```
rm _tmp_simple/active
ln -s backupXXXXX _tmp_simple/active
```
