### ISSUE TITLE
Export Decision Logs to S3

### ISSUE THREAD

**Issue by danoliver1** [open-policy-agent/opa#4883]
## What is the underlying problem you're trying to solve?

I would like to export the decision log history directly into an S3 bucket. This would allow decision logs to be queried using AWS Glue.

## Describe the ideal solution

This is my example config which I hoped would work but it seems S3 can only be used to pull bundles currently.

```
services:
  s3:
    url: https://my-bucket-name.s3.eu-west-2.amazonaws.com/
    credentials:
      s3_signing:
        web_identity_credentials:
          aws_region: eu-west-2
bundles:
  authz:
    service: s3
    resource: policies/default.tar.gz
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120
plugins:
  envoy_ext_authz_grpc:
      addr: :9191
      path: example/ingress/allow
      dry-run: false
      enable-reflection: false
decision_logs:
  service: s3
  console: true
```

The ideal solution would be as above. E.g. set `decision_logs.service` to the S3 service, and uploading to S3 would be automatically handled behind the scenes.

## Additional Context

In my example, the service is already configured to pull bundles from S3 so uploading the logs to the same bucket would be ideal.
As a workaround I could create a service to receive the decision logs via HTTP and upload to S3 but this seems like unnecessary extra complexity.
