### ISSUE TITLE
Add opa to `$PATH` in docker image

### ISSUE THREAD

**Issue by matusf** [open-policy-agent/opa#5003]
## What is the underlying problem you're trying to solve?
When running opa in the CI one needs to find out where is located. For example my current gitlab ci looks like this. I needed run the image and find that it is located at root. If it was is `$PATH`, one would not have to do this.

```yaml
test_policies:
  image: openpolicyagent/opa:0.43.0-debug
  script:
    - /opa test .
```

## Describe the ideal solution
Opa binary could be added to `$PATH`.
