### ISSUE TITLE
Decision_logs console logging

### ISSUE THREAD

**Issue by ShevtsovBohdan** [open-policy-agent/opa#5129]
## Short description 
When the decision_logs: console config option set to false, looks like OPA tries to send requests with decision_logs to an external service 

## Examples:
* OPA configuration: 

```
services:
  -name: ${authorization-service.name}
    url: "${authorization-service.host}:${authorization-service.port}"

discovery:
  name: discovery
  resource: "${authorization-service.resource}/${opa.service}"
  service: ${authorization-service.name}
  polling:
      min_delay_seconds: ${opa.discovery.polling.min.delay.seconds}
      max_delay_seconds: ${opa.discovery.polling.max.delay.seconds}
```

      
 * Discovery config 1:
 `{
    "discovery": {
        "bundles": {
            "tenant": {
                "service": "as",
                "resource": "",
                "polling": {
                    "min_delay_seconds": 20,
                    "max_delay_seconds": 40
                }
            }
        },
        "decision_logs": {
            "console": true
        }
    }
}`

*  Discovery config 2:
 `{
    "discovery": {
        "bundles": {
            "tenant": {
                "service": "as",
                "resource": "",
                "polling": {
                    "min_delay_seconds": 20,
                    "max_delay_seconds": 40
                }
            }
        },
        "decision_logs": {
            "console": false
        }
    }
}`

Note that the only change between config #1 and config #2 is decision_logs: console option value.

* OPA version: latest

## Steps To Reproduce
1. Use the discovery config 1
2. Verify that decision_logs is enabled
3. Use the discovery config 2
4. Verify that decision_logs is not disabled. OPA is trying to send lot of requests to service endpoint which is not configured

## Expected behavior
On step 4 the decision_logs should be disabled.
