### ISSUE TITLE
ref heads: generic refs

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#5247]
In #4660, we've added support for string prefixes:

```rego
package p

a.b.c[x] := y if { x := input.x; y := input.y }
```

("a" and "b" are the _strings_ here)

We could allow generic refs in rule heads:

```rego
package p

a[x].b[y] := z if {
  x := input.x
  y := input.y
  z := input.z
}
```
where `x` and `y` could have any type the want, both ground and non-ground.

For `input = {"x": "1", "y": "2", "z": "3"}`, we'd evaluate `data.p` to (yaml)
```yaml
a:
  "1":
    b:
      "2": "3"
```

The more interesting use is when there's more than one binding of a var:
```rego
package p
a[x].allow := x == "GET" if some x in {"GET", "PUT", "POST"}
```
would evaluate to
```yaml
a:
  GET:
    allow: true
  PUT:
    allow: false
  POST:
    allow: false
```

It'll require some changes to the RuleTree and topdown's evalVirtual logic.

This will come it with its own feature cap.
