### ISSUE TITLE
openpolicyagent/opa docker container fails to start on both github actions and circleci

### ISSUE THREAD

**Issue by jsteinberg-rbi** [open-policy-agent/opa#5324]
## Short description 
openpolicyagent/opa does not run on github actions or circleci.

Examples:
```
# from github actions

Checking docker version
Clean up resources from previous jobs
Create local container network
Starting job container
  /usr/bin/docker pull openpolicyagent/opa:0.45.0
  0.45.0: Pulling from openpolicyagent/opa
  79e0d[8](https://github.com/baseline-observability-poc/actions/runs/3352602117/jobs/5554851388#step:2:9)860fad: Pulling fs layer
  bf75762436b0: Pulling fs layer
  a1f1879bb7de: Pulling fs layer
  915d36c1c2c4: Pulling fs layer
  915d36c1c2c4: Waiting
  a1f1879bb7de: Download complete
  79e0d8860fad: Verifying Checksum
  79e0d8860fad: Download complete
  bf75762436b0: Verifying Checksum
  bf75762436b0: Download complete
  79e0d8860fad: Pull complete
  915d36c1c2c4: Verifying Checksum
  915d36c1c2c4: Download complete
  bf75762436b0: Pull complete
  a1f1879bb7de: Pull complete
  915d36c1c2c4: Pull complete
  Digest: sha256:385979a156dbe413fd894ffe85[11](https://github.com/baseline-observability-poc/actions/runs/3352602117/jobs/5554851388#step:2:13)ccd3f81a81858275c119d3984e68f604c53e
  Status: Downloaded newer image for openpolicyagent/opa:0.45.0
  docker.io/openpolicyagent/opa:0.45.0
  /usr/bin/docker create --name df5ad0956a2c43ea8948927db6e83883_openpolicyagentopa0450_86b83a --label 8d5581 --workdir /__w/cbaseline-observability-poc/baseline-observability-poc --network github_network_ef24d51fb6684ed6b0d9723b45597059  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.298.2/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" openpolicyagent/opa:0.45.0 "-f" "/dev/null"
  2217fd32076eaa43d4[15](https://github.com/rbilabs/ctg-baseline-observability-poc/actions/runs/3352602117/jobs/5554851388#step:2:18)abe3f6353f6e36e2b1[16](https://github.com/baseline-observability-poc/actions/runs/3352602117/jobs/5554851388#step:2:19)184991c8b7ac21deb1f49053
  /usr/bin/docker start 22[17](https://github.com/rbilabs/ctg-baseline-observability-poc/actions/runs/3352602117/jobs/5554851388#step:2:20)fd32076eaa43d415abe3f6353f6e36e2b116[18](https://github.com/rbilabs/ctg-baseline-observability-poc/actions/runs/3352602117/jobs/5554851388#step:2:21)4991c8b7ac21deb1f49053
  Error response from daemon: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "tail": executable file not found in $PATH: unknown
  Error: failed to start containers: 2217fd3[20](https://github.com/rbilabs/ctg-baseline-observability-poc/actions/runs/3352602117/jobs/5554851388#step:2:23)76eaa43d415abe3f6353f6e36e2b116184991c8b7ac[21](https://github.com/rbilabs/ctg-baseline-observability-poc/actions/runs/3352602117/jobs/5554851388#step:2:24)deb1f49053
  Error: Docker start fail with exit code 1
```

Unfortunately circleci does not provide any debug output method. I have attached a picture to show what circleci does show so that it is convincing that the opa image is successfully pulled, but similar to github fails to start.

<img width="1501" alt="Screen Shot 2022-10-29 at 2 38 03 PM" src="https://user-images.githubusercontent.com/108352663/198849805-4b630b3b-6d82-408b-8e1d-b5db8c905aed.png">

Fixing the github actions issue is in a sense straightfoward: it's looking for `tail` and running `opa:$tag-debug` solves that issue, although I'm not sure running the debug container is what is desired by the group. Regardless running debug does not resolve the issue with circleci.

Fwiw openpolicyagent/conftest _does_ run out of the box, as I'm sure most other openpolicyagent products do.

## Steps To Reproduce
```
# in a github repo
# mkdir .github/workflows
# touch .github/workflows/opa.yml
# inside opa.yml write

name: container
on: push

jobs:
  opa:
    runs-on: ubuntu-latest
    container:
      image: openpolicyagent/opa:0.45.0
    steps:
         - name: Test opa version
           run: |
             opa version
```

Also on circleci

```
# create dummy circleci account
# inside repo:
# touch config.yml

version: 2.1

jobs:
  opa:
    docker:
      - image: openpolicyagent/opa
    steps:
      - run:
           command: opa version

workflows:
  opa-test
    jobs:
      - opa

```

## Expected behavior
binary is located upon startup

## Additional Thoughts
The reason I'm raising this is because on the one hand I appreciate an OSS group's inability to cater to all systems, I'd imagine it's utterly impossible. Still: github actions is probably going to be the world's most popular simple CI workflow tool if it isn't already and circleci is a giant, comparatively, in the industry, so at the very least I think updating documentation to say, "hey fyi these containers don't work out of the box on these systems" would be very helpful. And maybe you can reach out to circle and find a stable path forward because I'm sure that the opa container not running on it without some hack is not what the group wants.
