### ISSUE TITLE
Discovery bundle persist location

### ISSUE THREAD

**Issue by sirpi** [open-policy-agent/opa#5644]
## Additional context

I've just tried the brand new 0.49.0 by adopting the new discovery bundle feature.
But because there is no persistence_directory implemented this case, I cannot use it since in my dockerized instance /opt/opa is read-only.
To be able to use this new feature, persistence_directory attribute would be essential to implement in accordance with the similar bundle feature. (and sorry for the coincise format, I am from my mobile)

**Comment by anderseknert** [comment]
It makes sense to me that discovery bundles are provided the option of a configurable persistence directory. However, you should still be able to mount a writable directory into `/.opa/bundles/`, right?

**Comment by anderseknert** [comment]
Oh, wait — from looking at the PR, it **does** look like the `persistence_directory` configuration is supported: https://github.com/open-policy-agent/opa/pull/5597/files#diff-2404c83a031cbabac204fe69d9b997b2b8f559eddb480335384fb88e5dbd737bR195

Did you try it and find it not working?

**Comment by sirpi** [comment]
I tried it locally and the discovery bundle has been stored in ./opa/bundles/... with the following config:

```
discovery:
  name: agent-config
  resource: configurations/discovery.tar.gz
  service: storage-service
  decision: config/discovery
  persist: true
  persistence_directory: /mnt/test
  signing:
    keyid: global_key
```

And the parameter in question is not documented either.

**Comment by anderseknert** [comment]
It is. See the configuration reference [here](https://www.openpolicyagent.org/docs/latest/configuration/#miscellaneous), and [here](https://www.openpolicyagent.org/docs/latest/configuration/#example) for an example. 

It's a top-level attribute, so your config should be updated to be something like:

```yaml
persistence_directory: /mnt/test

discovery:
  name: agent-config
  resource: configurations/discovery.tar.gz
  service: storage-service
  decision: config/discovery
  persist: true
  signing:
    keyid: global_key
```
