### ISSUE TITLE
[bundle] Support http bundle loading shorthand

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#5674]
## What is the underlying problem you're trying to solve?

I would like to be able to provide users with a quick way to start OPA with a remote bundle, e.g.

```
opa run -s https://example.com/bundle.tar.gz
```

Currently I must use a config file like this:

```yaml
services:
  example:
    url: http://localhost:8080

bundles:
  example:
    service: example
    resource: bundle.tar.gz
    persist: true
```

Or use `--set` many times:

```
opa run -s --set=services.example.url=http://localhost:8080 --set bundles.example.resource="bundle.tar.gz" --set bundles.example.service="example" --set bundles.example.persist="true"
```

This would make it harder for users new to OPA to understand what's going on or to follow a tutorial.

## Describe the ideal solution
Running a command like this:

```
opa run -s https://example.com/bundle.tar.gz
```

Would be a shorthand for:

```yaml
services:
  example:
    url: http://localhost:8080

bundles:
  example:
    service: example
    resource: bundle.tar.gz
    persist: true
```

## Describe a "Good Enough" solution

OPA could instead stash the file in a temp dir and load it from that. However, it'd be nice to be able to reuse the bundle loading configuration to access features such as persistence so that users can reuse downloaded bundles.

## Additional Context

Related to: https://github.com/open-policy-agent/opa/issues/5673
