### ISSUE TITLE
Bundle refresh

### ISSUE THREAD

**Issue by andrewcamilleri** [open-policy-agent/opa#5737]
Upgrading from `opa:0.48.0-rootless` to `opa:0.49.2-rootless`, without any code changes, we started to get an error of the type  `multiple default rules data.system1.wpt.allow found`. Our policies are organised into packages so that we can check `allow` for any `system[N]`, but this happens even when we have a single `system` policy i.e. we removed all other policies except one.

After careful investigation it appears that the issue is with how the bundle gets refreshed. Our setup is simple; we have an opa sidecar that refreshes the policies every few seconds using the following conf:

```
services:
  - name: service
    url: http://docker.for.mac.localhost:8080/v1
    credentials:
      bearer:
        token: TOKEN

bundle:
  name: bundle.tar.gz
  prefix: bundle
  service: service
  polling:
    min_delay_seconds: 10
    max_delay_seconds: 20
```

We issue `allow` type requests like this: `POST /v1/data/system/wpt/allow`.
The error we encounter happens as soon as the bundle gets refreshed. It fails with `multiple default rules data.system.wpt.allow found` on the first request, but succeeds all the subsequent ones, until the bundle gets refreshed.

I discussed this in slack: https://openpolicyagent.slack.com/archives/CBR63TK2A/p1678108747073019

I am attaching a sample bundle.

[bundle.zip](https://github.com/open-policy-agent/opa/files/10920011/bundle.zip)

**Comment by charlieegan3** [comment]
Hi @andrewcamilleri, thanks for filing this issue.

I set up file server serving your bundle. I then started OPA with similar config to the above. After the bundle had loaded correctly the first time, I waited and saw that OPA refreshes the bundle for a second time without issue.

> After careful investigation it appears that the issue is with how the bundle gets refreshed

You explain that you see the error when the bundle is refreshed. Is the bundle content changing? Also, are you loading in any other bundles to the OPA instance which have policies or data at other paths?

**Comment by andrewcamilleri** [comment]
No we are not loading anything else. We have other rego files, but we get the error even with this single rego policy.
The bundle might change, but in our testing environment this does not change. The only thing that might change is the `data.json` which contains the user membership groups.

**Comment by charlieegan3** [comment]
I see. Hopefully that will make it easier to narrow down.

Do you have a series of commands you can run to locally replicate the issue? I can't seem o get my OPA to misbehave with the data you have sent so far.

**Comment by andrewcamilleri** [comment]
This is docker compose we use:

```
version: "3.9"
services:
  dynamo:
    image: "amazon/dynamodb-local"
    environment:
      - ./Djava.library.path=./DynamoDBLocal_lib
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

  opa:
   image: "openpolicyagent/opa:0.49.2-rootless"
   ports:
    - 8181:8181
   volumes:
    - .:/bundle
   command:
    - "run"
    - "--server"
    - "-c"
    - "/bundle/opa.yaml"
```

The bundle is generated on the fly from our go app
