### ISSUE TITLE
YAML on/off as keys cannot be queried correctly

### ISSUE THREAD

**Issue by scnewma** [open-policy-agent/opa#5754]
## Short description 

When using a YAML file as a data input, object keys that are YAML keywords are not converted correctly to JSON. A common example is `on` which is commonly used in [Github Actions YAML](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on). When loaded as data, the `on` object key is converted to `true` instead.

opa version: `0.50.0`

## Steps To Reproduce

**data.yaml**

```yaml
on: push
```

**example.rego**

```
package example

import future.keywords.if

default is_push := false

is_push if input.on == "push"
```

Evaluate a basic OPA query to check if `on` is equal to `"push"`:

```sh
❯ opa eval --data data.yaml 'is_push := data.on == "push"'
{}
```

## Expected behavior

Able to query for the `on` field and get data back.

## Additional context

This happens because `on` is converted to `true` in the key, as can be seen with this query:

```sh
❯ opa eval --data data.yaml 'data'
{
  "result": [
    {
      "expressions": [
        {
          "value": {
            "true": "push"
          },
          "text": "data",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

This happens with `off` keyword as well (it's converted to `false`):

**data.yaml**

```yaml
off: some-value
```

```sh
❯ opa eval --data data.yaml 'data'
{
  "result": [
    {
      "expressions": [
        {
          "value": {
            "false": "some-value"
          },
          "text": "data",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

**Comment by anderseknert** [comment]
Thanks for reporting this, @scnewma! YAML truly is a cursed format.

**Comment by anderseknert** [comment]
Some digging into this, and OPA even mentioned in this issue from a year ago: https://github.com/ghodss/yaml/issues/77
The library we're using seems to be abandonded, and the fork which apparently fixes this doesn't look super active either. Not a great situation, but might be worth making the switch still.

**Comment by scnewma** [comment]
Good find! After some more poking, I found that the Kubernetes project has their own fork of ghodss/yaml as well here: https://github.com/kubernetes-sigs/yaml. It looks like they [weren't able to simply upgrade from go-yaml v2 to v3](https://github.com/kubernetes-sigs/yaml/pull/61), though from a quick glance it's hard to tell if that's because of something Kubernetes specific vs changes to the library.

**Comment by scnewma** [comment]
Forgot to add more details. I tried that and because that library has not updated to go-yaml v3 it still has the on/off bug 😞 . I believe the only option may be the fork that you mentioned in your first link.

**Comment by anderseknert** [comment]
Thanks @scnewma! Sounds like it'd be worth investigating that option then 👍

**Comment by anderseknert** [comment]
Related 🤦 https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell

**Comment by ViacheslavKudinov** [comment]
Hi,
any updates here?
Got same issue with yaml like this one (GitHub reusable workflow):
```
on:
  workflow_call:
    inputs:
      java-version:
        description: "The java-version input supports an exact version or a version range using SemVer notation: major versions: 8, 11, 16, 17. more specific versions: 17.0, 11.0, 11.0.4, 8.0.232, 8.0.282+8 early access (EA) versions: 15-ea, 15.0.0-ea, 15.0.0-ea.2, 15.0.0+2-ea"
        required: true
        type: string
      java_distribution:
        description: 'Currently, the following distributions are supported: `"temurin"` (Eclipse Temurin), `"zulu"` (Zulu OpenJDK), `"adopt"` (Adopt OpenJDK Hotspot), `"adopt-openj9"` (Adopt OpenJDK OpenJ9).'
        required: false
        default: "temurin"
        type: string
```
