### ISSUE TITLE
OCI: fail to download public bundles via without credentials

### ISSUE THREAD

**Issue by carabasdaniel** [open-policy-agent/opa#5902]
With the latest changes in v0.52.0 the OCI downloader returns a 401 error from ghcr.io when trying to download a public policy image.

Example configuration (example-file.yaml) :
```
services:
  ghcr-registry:
    url: https://ghcr.io/
    type: oci

bundles:
  acme:
    service: ghcr-registry
    resource: ghcr.io/carabasdaniel/testpol:latest
```

## Steps To Reproduce
`opa run -c example-file.yaml `

Logs:
```
{"level":"error","msg":"Bundle load failed: failed to pull ghcr.io/carabasdaniel/testpol:latest: download for 'ghcr.io/carabasdaniel/testpol:latest' failed: failed to resolve ghcr.io/carabasdaniel/testpol:latest: pulling from host ghcr.io failed with status code [manifests latest]: 401 Unauthorized","name":"acme","plugin":"bundle","time":"2023-05-04T20:04:22+03:00"}
```

## Expected behavior
Load bundle successfully from public image.

## Additional context
I suspect the problem might be related to the authorizer used here https://github.com/open-policy-agent/opa/blob/main/download/oci_download.go#L333 when there are no credentials/plugins configured.
