### ISSUE TITLE
Move Istio from EnvoyFilter to AuthorizationPolicy

### ISSUE THREAD

**Issue by howardjohn** [open-policy-agent/opa#5911]
Currently OPAs Istio docs are using EnvoyFilter which is fragile/alpha/not recommended where possible. Authorization Policy has first class support for ext_authz now: https://istio.io/latest/docs/tasks/security/authorization/authz-custom/.

The different between the two seems to be usage of google_grpc in the EnvoyFilter:
```yaml
            grpc_service:
              # NOTE(tsandall): when this was tested with the envoy_grpc client the gRPC
              # server was receiving check requests over HTTP 1.1. The gRPC server in
              # OPA-Istio would immediately close the connection and log that a bogus
              # preamble was sent by the client (it expected HTTP 2). Switching to the
              # google_grpc client resolved this issue.
              google_grpc:
                target_uri: 127.0.0.1:9191
                stat_prefix: "ext_authz"
```

However, I think this is just a misconfiguration of Istio likely, missing the declaration of the service as HTTP. See https://istio.io/latest/docs/tasks/security/authorization/authz-custom/#deploy-the-external-authorizer.

I think it would be great to move this over, and we (Istio team; I am a maintainer) are happy to help.
