### ISSUE TITLE
Command opa run --server --bundle=/root/rego/files failing to run from kubernetes

### ISSUE THREAD

**Issue by gianielsevier** [open-policy-agent/opa#5922]
## Short description 
Opa 0.52.0 docker image is failing to startup the server running on k8s when the -b or --bundle argument is provided
I'm creating a configMap where the .rego and .manifest are located
The deployment has a volume and volumeMount using the configMap where the files are located

Examples:

* OPA version: 0.52.0
* ConfigMap:
---
```yaml
# Source: opa/templates/autzconfigmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: authz-map
data:
  .manifest: |
    {
      "revision": "0.0.1",
      "roots": [
        "system/authz"
      ]
    }
  basic_auth.rego: |-
    package system.authz
  
    expectedCredential = opa.runtime().env.OPA_ADMIN_CREDENTIALS
  
    default allow := {
        "allowed": false
    }
  
    allow := { "allowed": true } {  # Allow request if...
        credentialString = getCredentialFromRequest(input)
        credentialString == expectedCredential
    }
  
    allow := { "allowed": true } {
        input.method == "POST"
    }
  
    allow := { "allowed": false, "reason": reason } {
        expectedCredential != getCredentialFromRequest(input)
        print("from auth: ", getCredentialFromRequest(input))
        print("expected: ", expectedCredential)
        input.method != "POST"
        reason := "invalid credential for non-POST requests"
    }
  
    getCredentialFromRequest(requestInput) := value {
        header := input.headers.Authorization[0]
        startswith(header, "Basic ")
        credential := trim_prefix(header, "Basic ")
        value = base64url.decode(credential)
    }
```
* Deployment:
```yaml
# Source: opa/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-opa
  labels:
    helm.sh/chart: opa-0.2.0
    app.kubernetes.io/name: opa
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: opa
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        kube-secret-inject: "true"
        
      labels:
        kube-secret-inject: "true"
        app.kubernetes.io/name: opa
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: 
      securityContext:
        {}
      containers:
        - name: 
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
          image: "openpolicyagent/opa:latest"
          imagePullPolicy: IfNotPresent
          command: 
            ["/opa"]
          args:
            - --server
            - --ignore=.*
            - --log-format=json
            - --set=decision_logs.console=true
            - --config-file=/var/opa/config/config.yaml
            - --authorization=basic
            - --bundle /authz
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          startupProbe:
            failureThreshold: 48
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 300Mi
          volumeMounts:
            - name: var-opa
              mountPath: /var/opa
            - name: var-opa-config
              mountPath: /var/opa/config
            - name: authz
              mountPath: /authz
      volumes:
        - name: var-opa
          emptyDir:
            sizeLimit: 10Mi
        - name: var-opa-config
          configMap:
            name: opa-config-map
        - name: authz
          configMap:
            name: authz-map
```
* Error:
```ssh
Error: unknown flag: --bundle /path                                                                                                                                                                      Usage:                                                                                                                                                                                                    
opa run [flags] [files]
Flags:
-a, --addr strings                         set listening address of the server (e.g., [ip]:<port> for TCP, unix://<path> for UNIX domain socket) (default [:8181])
--authentication {token,tls,off}       set authentication scheme (default off)
...
```

## Steps To Reproduce
1. Create the configMap into your K8s cluster
2. Deploy the pods into your k8s cluster
4. Open the logs of the POD and see the error

## Expected behavior
Opa server startup and load the bundle provided --bundle argument
