### ISSUE TITLE
When deploying the OPA service using Docker, folders with names starting with _MEI are periodically generated in the /tmp directory on the host machine.

### ISSUE THREAD

**Issue by Lockeysama** [open-policy-agent/opa#5990]
## Short description 

When deploying the OPA service using Docker, folders with names starting with _MEI are periodically generated in the /tmp directory on the host machine.

* The content of deployment file (`docker-compose.yaml`)：
```yaml
version: '3.8'

networks:
  bridge:
    external:
      name: bridge

services:
  opa:
    image: openpolicyagent/opa:0.53.1
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--log-level=info"
      - "--config-file=/config/config.yaml"
    volumes:
      - "./config:/config"
    network_mode: bridge
```

* The content of config file:
```yaml
services:
  - name: iam
    url: http://10.0.0.6:50000

bundles:
  iam:
    service: iam
    resource: api/iam/bundles/package/v1/bundle.tar.gz
    polling:
      min_delay_seconds: 300
      max_delay_seconds: 600

decision_logs:
  console: true

status:
  console: true

default_decision: /iam/allow
```

## Expected behavior

It does not affect the host machine, and the automatically generated files can be cleaned up automatically.

## Additional context

The generated folder names and content might look like this:

`> ls /tmp`
```
drwx------ 15 root root  4096 Jun  8 14:36 _MEIIrbhlw
drwx------ 15 root root  4096 Jun  8 14:56 _MEILFEBhi
drwx------ 15 root root  4096 Jun  8 14:35 _MEILZCKxP
drwx------ 15 root root  4096 Jun  8 14:57 _MEIM1evKh
drwx------ 15 root root  4096 Jun  8 14:41 _MEIMW9cke
drwx------ 15 root root  4096 Jun  8 14:37 _MEIMokdcC
drwx------ 15 root root  4096 Jun  8 14:51 _MEINWwlqu
drwx------ 15 root root  4096 Jun  8 14:41 _MEIO0J3Hk
drwx------ 15 root root  4096 Jun  8 14:56 _MEIO7HNLi
drwx------ 15 root root  4096 Jun  8 14:55 _MEIOQQT8x
drwx------ 15 root root  4096 Jun  8 14:40 _MEIOvLV5m
drwx------ 15 root root  4096 Jun  8 14:41 _MEIPCkknt
drwx------ 15 root root  4096 Jun  8 14:38 _MEIPx4axh
drwx------ 15 root root  4096 Jun  8 14:38 _MEIRmUWVc
drwx------ 15 root root  4096 Jun  8 14:53 _MEIS9co4V
drwx------ 15 root root  4096 Jun  8 14:38 _MEISH8GKc
drwx------ 15 root root  4096 Jun  8 14:52 _MEITGmXNl
drwx------ 15 root root  4096 Jun  8 14:39 _MEITZhReR
drwx------ 15 root root  4096 Jun  8 14:51 _MEIUTSplC
drwx------ 15 root root  4096 Jun  8 14:54 _MEIUU9lwN
drwx------ 15 root root  4096 Jun  8 14:54 _MEIUi6pTQ
drwx------ 15 root root  4096 Jun  8 14:52 _MEIVwcX6n
drwx------ 15 root root  4096 Jun  8 14:55 _MEIWNWAzy
drwx------ 15 root root  4096 Jun  8 14:36 _MEIWvsO9E
drwx------ 15 root root  4096 Jun  8 14:54 _MEIXA4HtR
drwx------ 15 root root  4096 Jun  8 14:53 _MEIXHGO2d
drwx------ 15 root root  4096 Jun  8 14:53 _MEIXcY35W
drwx------ 15 root root  4096 Jun  8 14:41 _MEIY94SDl
drwx------ 15 root root  4096 Jun  8 14:52 _MEIYNMx8t
drwx------ 15 root root  4096 Jun  8 14:39 _MEIYhUHmU
drwx------ 15 root root  4096 Jun  8 14:41 _MEIZOyrsd
```

`> ls _MEIIrbhlw`
```
_asyncio.cpython-37m-x86_64-linux-gnu.so          bcrypt
_bisect.cpython-37m-x86_64-linux-gnu.so           binascii.cpython-37m-x86_64-linux-gnu.so
_blake2.cpython-37m-x86_64-linux-gnu.so           certifi
_bz2.cpython-37m-x86_64-linux-gnu.so              compose
_cffi_backend.cpython-37m-x86_64-linux-gnu.so     cryptography
_codecs_cn.cpython-37m-x86_64-linux-gnu.so        cryptography-3.3.2-py3.7.egg-info
_codecs_hk.cpython-37m-x86_64-linux-gnu.so        fcntl.cpython-37m-x86_64-linux-gnu.so
_codecs_iso2022.cpython-37m-x86_64-linux-gnu.so   grp.cpython-37m-x86_64-linux-gnu.so
_codecs_jp.cpython-37m-x86_64-linux-gnu.so        importlib_metadata-3.10.1-py3.7.egg-info
_codecs_kr.cpython-37m-x86_64-linux-gnu.so        include
_codecs_tw.cpython-37m-x86_64-linux-gnu.so        jsonschema
_contextvars.cpython-37m-x86_64-linux-gnu.so      jsonschema-3.2.0-py3.7.egg-info
_csv.cpython-37m-x86_64-linux-gnu.so              lib
_ctypes.cpython-37m-x86_64-linux-gnu.so           libbz2.so.1.0
_datetime.cpython-37m-x86_64-linux-gnu.so         libcrypto.so.1.1
_decimal.cpython-37m-x86_64-linux-gnu.so          libexpat.so.1
_hashlib.cpython-37m-x86_64-linux-gnu.so          libffi-806b1a9d.so.6.0.4
_heapq.cpython-37m-x86_64-linux-gnu.so            libffi.so.6
_json.cpython-37m-x86_64-linux-gnu.so             liblzma.so.5
_lzma.cpython-37m-x86_64-linux-gnu.so             libpython3.7m.so.1.0
_md5.cpython-37m-x86_64-linux-gnu.so              libreadline.so.7
_multibytecodec.cpython-37m-x86_64-linux-gnu.so   libssl.so.1.1
_multiprocessing.cpython-37m-x86_64-linux-gnu.so  libtinfo.so.5
_opcode.cpython-37m-x86_64-linux-gnu.so           libuuid.so.1
_pickle.cpython-37m-x86_64-linux-gnu.so           libz.so.1
_posixsubprocess.cpython-37m-x86_64-linux-gnu.so  math.cpython-37m-x86_64-linux-gnu.so
_queue.cpython-37m-x86_64-linux-gnu.so            mmap.cpython-37m-x86_64-linux-gnu.so
_random.cpython-37m-x86_64-linux-gnu.so           nacl
_sha1.cpython-37m-x86_64-linux-gnu.so             pvectorc.cpython-37m-x86_64-linux-gnu.so
_sha256.cpython-37m-x86_64-linux-gnu.so           pyexpat.cpython-37m-x86_64-linux-gnu.so
_sha3.cpython-37m-x86_64-linux-gnu.so             readline.cpython-37m-x86_64-linux-gnu.so
_sha512.cpython-37m-x86_64-linux-gnu.so           resource.cpython-37m-x86_64-linux-gnu.so
_socket.cpython-37m-x86_64-linux-gnu.so           select.cpython-37m-x86_64-linux-gnu.so
_ssl.cpython-37m-x86_64-linux-gnu.so              termios.cpython-37m-x86_64-linux-gnu.so
_struct.cpython-37m-x86_64-linux-gnu.so           unicodedata.cpython-37m-x86_64-linux-gnu.so
_uuid.cpython-37m-x86_64-linux-gnu.so             wcwidth
array.cpython-37m-x86_64-linux-gnu.so             yaml
base_library.zip                                  zlib.cpython-37m-x86_64-linux-gnu.so
```
