### ISSUE TITLE
Use multiple OCI containers as Bundles

### ISSUE THREAD

**Issue by abdullahalrifat** [open-policy-agent/opa#6313]
i am trying to load 2 different bundle in OPA
i am building bundle
`/opa build -b $DEFAULT_OPA_TEMP_STORAGE/opa --optimize=1 --entrypoint "authz/def/allow"`

`/opa build -b $DEFAULT_OPA_TEMP_STORAGE/noop --optimize=1 --entrypoint "authz/noop/allow"`

and pushing as OCI containers in registry
```
services:
  harbor-registry:
    url: https://dummy-reg.io/
    type: oci

bundles:
  authz/def:
    service: harbor-registry
    resource: https://dummy-reg.io/policy-default:latest
    persist: true
    polling:
      min_delay_seconds: 30
      max_delay_seconds: 120
  authz/noop:
    service: harbor-registry
    resource: https://dummy-reg.io/policy-noop:latest
    persist: true
    polling:
      min_delay_seconds: 30
      max_delay_seconds: 120
```
these are the 2 .manifest files
one contains a multiple rego and data files
```
package authz.def

import input.attributes.request as http_request
import data.library.configuration
...
import future.keywords
....
default allow = false
...
...
```
```
{
  "revision" : "0.0.1",
  "roots": ["library", "dev", "qa", "prod", "system", "authz/def", "integration-test"]
}
```
another plain and simple rego file
```
package authz.noop

default allow = true
result["allowed"] = true
result["http_status"] = 200
```
```
{
  "revision" : "0.0.1",
  "roots": ["authz/noop"]
}
```
and when i try to run
`./opa run --server --set default_decision=policies --log-level=debug --log-format=json-pretty  -c ./configuration.yaml`
i get
```
{
  "level": "error",
  "msg": "Bundle activation failed: detected overlapping roots in bundle manifest with: [authz/noop]",
  "name": "authz/def",
  "plugin": "bundle",
  "time": "2023-10-13T09:39:11Z"
}
```
i tried updating the package name
authz/noop -> noop
authz/def -> def
result
```
{
  "level": "error",
  "msg": "Bundle activation failed: detected overlapping roots in bundle manifest with: [noop]",
  "name": "def",
  "plugin": "bundle",
  "time": "2023-10-13T09:56:33Z"
}
```
