### ISSUE TITLE
Envoy external auth and UDS example tutorial does't work

### ISSUE THREAD

**Issue by Sanskarzz** [open-policy-agent/opa#6757]
## Short description 

This example [tutorial](https://github.com/open-policy-agent/opa-envoy-plugin/tree/main/examples/envoy-uds) on opa-envoy-plugin with UDS does't work .

cc @ashutosh-narkar

it returns 403 forbidden on both get and post curl request. 
```console
sanskar@sanskar-HP-Laptop-15s-du1xxx:~/opa-envoy-plugin/examples/envoy-uds$ curl -i -H "Authorization: Bearer "$ALICE_TOKEN"" http://$SERVICE_URL/people
HTTP/1.1 403 Forbidden
date: Thu, 23 May 2024 10:17:01 GMT
server: envoy
content-length: 0

sanskar@sanskar-HP-Laptop-15s-du1xxx:~/opa-envoy-plugin/examples/envoy-uds$ curl -i -H "Authorization: Bearer "$ALICE_TOKEN"" -d '{"firstname":"Charlie", "lastname":"OPA"}' -H "Content-Type: application/json" -X POST http://$SERVICE_URL/people
HTTP/1.1 403 Forbidden
date: Thu, 23 May 2024 10:17:08 GMT
server: envoy
content-length: 0
```

**Comment by ashutosh-narkar** [comment]
Thanks for reporting this @Sanskarzz. If you'd like to contribute a fix that would be great! Thanks.

**Comment by Sanskarzz** [comment]
@ashutosh-narkar   Yes, I would like to contribute. However, I have tried debugging and checking the Envoy logs to identify the problem, but I couldn't find a solution. It would be great if you could guide me or provide me with the steps to follow to resolve this issue.

**Comment by Sanskarzz** [comment]
Hey @ashutosh-narkar Are you sure `grpc_service.google_grpc.target_uri` field in envoy config supports unix domain sockets (uds) , just asking because i have not found any documentation on that .

```yaml
- name: envoy.ext_authz
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                  transport_api_version: V3
                  with_request_body:
                    max_request_bytes: 8192
                    allow_partial_message: true
                    pack_as_bytes: true
                  failure_mode_allow: false
                  grpc_service:
                    google_grpc:
                      stat_prefix: ext_authz
                      target_uri: unix:///run/opa/sockets/auth.sock
                    timeout: 0.5s
```
