### ISSUE TITLE
OpenTelemetry tracing request specific header attribute

### ISSUE THREAD

**Issue by rasmuscc** [open-policy-agent/opa#7077]
## What is the underlying problem you're trying to solve?

We are sending a REST request in OPA with a request specific header and would like to include this header in the OpenTelemetry span as an attribute.
E.g. using: [http.response.header.<key>](https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/)

## Describe the ideal solution

I'd imagine it could be configured something like this:
```
distributed_tracing:
  type: "grpc"
  attributes:
    headers:
      - header1
```
Should produce a span like this:
![image](https://github.com/user-attachments/assets/01e445fe-ef91-4af0-b9ea-ac398e1f5b68)
