### ISSUE TITLE
Load multiple policy bundles

### ISSUE THREAD

**Issue by stan-podolski** [open-policy-agent/opa#721]
I'm trying to find a way to load policies from different bundles into the same OPA instance. So far I was unable to do so as you can only specify 1 bundle in the config file (https://www.openpolicyagent.org/docs/bundles.html). However, it is possible to specify multiple number of services from where bundle can be downloaded.

If this is not supported - what is the recommended way to load policies from different sources into the same OPA instance?

Thanks!

**Comment by stan-podolski** [comment]
Hi @tsandall, my use case is such that I have a number of independent teams, which manage their individual policies. They also have independent release cycles.
I wanted to set up an instance of OPA so it will go and pick up the latest release bundles for all teams.
Agree that it is possible to combine all policies into a single bundle ( thats what we gonna end up doing most likely), was just wondering if we could avoid that additional step.

**Comment by tsandall** [comment]
That makes sense.

By restricting the agent to a single bundle, we ensure that the bundle management is largely orthogonal to other capabilities in OPA. For example, OPA does not have to map policy decisions => bundles in the event log. Another example, is optimization; administrators could reasonably expect OPA to be optimize across bundles (e.g., by deduplicating the data.) Hope this helps.

I'm going to close this issue for now. If you have other questions feel free to post issues or ask us on [Slack](http://slack.openpolicyagent.org).

**Comment by tsandall** [comment]
I'm re-opening this issue because a few users have requested it. Now that we let bundles declare the root(s) they own, we could have multiple (non-overlapping) bundles loaded at once. The status and decision log plugins will need to take multiple bundles into account:

* Status should report the status of each bundle activation
* Decision Logs should include the revision of each bundle in events

**Comment by patrick-east** [comment]
I've been poking around at this and have a proposal for some changes, would be great to get some feedback from folks who would want to use this. I want to make sure we can handle the desired use-cases nicely.

## Proposed Changes

### Config

Currently we configure bundles with a map like:

```yaml
services:
  acmecorp:
    url: https://example.com/service/v1

bundle:
  name: authz/bundle.tar.gz
  prefix: somedir
  service: acmecorp
```

We already support multiple services like:

```yaml
services:
  acmecorp:
    url: https://example.com/service/v1
  hooli:
    url: https://hooli.com/service/

bundle:
  name: authz/bundle.tar.gz
  prefix: somedir
  service: acmecorp
```

The new config supported for `bundles` would change to use a map
similar to what the services is using. I see a couple options for what
we use for the keys..

#### Option 1
Key == `name` from older style config:

```yaml
services:
  acmecorp:
    url: https://example.com/service/v1
  hooli:
    url: https://hooli.com/service/

bundle:
  authz/bundle.tar.gz: 
    prefix: somedir
    service: acmecorp
  other/bundle.tar.gz: 
    prefix: somedir
    service: hooli
```
This keeps the naming and look/feel similar to services. The downside
is that the bundle `name` means more to bundle config than services.
It usually is going to be a like actual file name rather than just a unique identifier.

Alternatively we could use an alias for the key instead of `name`, which makes things
more human readable and lets people use `bundle.tar.gz` for all their bundle names.

#### Option 2

```yaml
services:
  acmecorp:
    url: https://example.com/service/v1
  hooli:
    url: https://hooli.com/service/

bundle:
  acmecorp:
    name: authz/bundle.tar.gz
    prefix: somedir
    service: acmecorp
  hooli:
    name: authz/bundle.tar.gz
    prefix: somedir
    service: hooli
```

In this format the yaml key is just an alias which would probably only surface in logs and status updates. The drawback here is that there are essentially two `name`s for each bundle.

We could change the `name` keyword to something like `path` or `resource`
but it might make the configuration kind of confusing between the older
and newer styles.

**I'm leaning towards option 2 here**

#### Bundle Root config
We already allow for setting a root for the bundle to manage in
their manifest. However with multiple bundles, potentially managed
by different teams (as described in one of the use-cases for this),
it might be kind of hard to coordinate or enforce which bundle gets
which roots. It could be really bad if some bundle took over a different
ones roots, either accidentally or maliciously.

I am proposing a new config option for the bundles that specify
what their allowed roots are with a list of glob options like:

```yaml
services:
  acmecorp:
    url: https://example.com/service/v1
  hooli:
    url: https://hooli.com/service/

bundle:
  acmecorp:
    name: authz/bundle.tar.gz
    prefix: somedir
    service: acmecorp
    allowed_roots:
      - "authz"
      - "other/authz/*"
  hooli:
    name: authz/bundle.tar.gz
    prefix: somedir
    service: hooli
    allowed_roots:
      - "hooli-authz/*"
```

We can then reject bundles with a manifest specifying roots that do
not match these ones. We also don't have to
worry about ordering issues since we can, at startup/config change,
enforce that the `allowed_roots` are not overlapping. I don't think
we need to make this required, but we should highly recommend it.

### /health Changes

We have a parameter to allow for including bundle status in the health
check. We will have to update it to wait for *all* bundles to have been
ready for the first time.

We could potentially add another parameter to specify which bundles to
consider.. This will *not* be supported in the first version of this.

### Status API Changes

The status API defines a payload that looks very similar to the original
bundles config where everything is a flat map. We will have to adjust this
to use a newer format with the bundle maps *or* send multiple status updates
(one per bundle).

The current proposal is to include all bundles configured in the status payload
to make it easier to get status on each (less work for the caller). To do this
I am proposing a new `version` field in the payload and changing the structure
to match the new config. For example:

Old Request:
```http
POST /status[/<partition_name>] HTTP/1.1
Content-Type: application/json
```

```json
{
    "labels": {
        "app": "my-example-app",
        "id": "1780d507-aea2-45cc-ae50-fa153c8e4a5a",
        "version": "v0.12.0"
    },
    "bundle": {
        "name": "http/example/authz",
        "active_revision": "TODO",
        "last_successful_download": "2018-01-01T00:00:00.000Z",
        "last_successful_activation": "2018-01-01T00:00:00.000Z"
    }
}
```


New Request:
```http
POST /status[/<partition_name>] HTTP/1.1
Content-Type: application/json
```

```json
{
    "version": "2",
    "labels": {
        "app": "my-example-app",
        "id": "1780d507-aea2-45cc-ae50-fa153c8e4a5a",
        "version": "v0.12.0"
    },
    "bundles": {
        "acmecorp": {
            "name": "http/example/authz",
            "active_revision": "123",
            "last_successful_download": "2018-01-01T00:00:00.000Z",
            "last_successful_activation": "2018-01-01T00:00:00.000Z"
        },
        "hooli": {
            "name": "http/example/authz",
            "active_revision": "876",
            "last_successful_download": "2018-01-01T00:00:00.000Z",
            "last_successful_activation": "2018-01-01T00:00:00.000Z"
        }
    }
}
```

To support backwards compatibility we can use a config option
in the `status` section to specify what API version to use:

```yaml
status:
  service: acmecorp
  version: 2
```

Where version 1 is the older style, and can be the default. Maybe for
OPA 1.0.0 we can swap them and break old configs.

If left set to version 1 (or left as default) *and* configured to use
multiple bundles we will raise an error in the runtime. The documentation
for bundles and status API will need to be updated to reflect this.

### Internal Changes of note
* Update discovery code to handle >1 bundle plugin
* For each bundle configured instantiate a bundle plugin for it
* Update status and server plugin listener to aggregate status from all bundle plugins


Will update the proposal as investigation/coding continues.

**Comment by tsandall** [comment]
* Config option (2) looks best to me. The 'bundle' and 'bundles' keys can be mutually exclusive. The docs can be updated to use 'bundles' throughout. 'bundle' can be supported until we decide to remove it (pre-1.0?)

* Bundle Root config. This seems like a good idea. Can we treat it as follow-on work?

* /health changes. Also seems like a good idea. Agreed that this can be follow-on work.

* Status API changes. I didn't expect to see the "version" field since these changes are additive. My expectation was that if a single "bundle" was configured, the status update would have the existing "bundle" field. If multiple "bundles" were configured, the status update would have the new "bundles" field.

* We'll also need to update the decision log events to support multiple revisions.

* The bundle manifest is written into the storage at /system/bundle/manifest. There are helper functions in internal/manifest to read the bundle revision and roots out of storage. The server uses these helpers to get the revision to include in decision log events and check for write conflicts. We'll need to update the server to deal with multiple revisions/roots. We should consider exposing the revision lookup so that the opa-istio[1] and other Go embeddings[2] do not have to re-implement the logic :scream: 

[1] https://github.com/open-policy-agent/opa-istio-plugin/blob/master/internal/internal.go#L35
[2] https://github.com/open-policy-agent/example-api-authz-go/blob/master/internal/opa/opa.go#L86

**Comment by patrick-east** [comment]
Thanks @tsandall ! I had totally missed the decision logger changes and that we read the manifest out of storage like that. Will update to account for them and the manifest storage stuff.

I'll remove the version field from the status API, IIRC the first write up of this I re-used the `bundle` key and changed the format then later switched to `bundles`. If we go with the new key we don't need it. I'm all in favor of that approach.

For the bundle root config I'm not sure if we want to wait on this. The solution is partially for security but also for ordering. For example, if we have two bundles with overlapping roots we can't guarantee the order we download/process/activate the bundles. So one bundle might get downloaded and take some root over, then the second one tries and fails to activate.. OPA might still be handling requests but not giving the same responses as if the second bundle had been activated first.

I spent some time thinking through other ways to handle this.. we could batch together activations and check roots on all configured bundles before activating any of them. If we find any conflicts we could de-activate/remove the older (currently being used) version of all conflicting bundles. The downside is that we lose some flexibility with different configured poll rates, or if say one server is temporarily offline or slow it could block all the other bundles from updating. It also means OPA keeps running but is giving bad (probably error) responses for requests it could have otherwise been handling.

Another crazy idea is having some sort of hierarchy or policy to decide which bundle in conflicting bundles wins... The complexity seemed to heavily outweigh the benefits though.

The crux of the problem is that the bundle gets to decide what it owns. IMO any approach we take with this should push the final decision for that to the OPA service (whether through config or internal policy). We just need to make sure bundles don't come in and declare they own some root that overlaps with someone elses.

So, the solution I like is that the admin instead draws lines in the sand and says bundle A owns namespace foo and bundle B owns namespace bar. They can do whatever they want in those namespaces, but if they break out of them they are in trouble (and only that bundle). We also don't have to worry about timing. If each of those configured roots updates at different times we can be assured that they won't just remove/rewrite everything in someone elses. It might still affect the evaluation results if they are importing from some other namespace.. but IMO that is on the policy author and deployer to coordinate.

**Comment by tsandall** [comment]
Sounds good. Thanks for thinking through the edge cases/attack vectors nonetheless!

**Comment by tsandall** [comment]
Read through the updates. I have a couple thoughts.

1. Joining the path prefix and bundle name into resource might be problematic for Status services because if they want _just the bundle name_ then they have to strip the prefix (...but they can't differentiate between the two.) We could tell people define multiple services (each with a different path) however then we have to duplicate the credentials and other service-level config.

2. Can we avoid the extra identifier in the bundle config?

Proposal (list format):

```yaml
bundles:
  - name: authz/bundle.tar.gz
    prefix: somedir
    service: acmecorp
```

OR (object format):

```yaml
bundles:
  authz/bundle.tar.gz:
    prefix: somedir
    service: acmecorp
```

3. In the current proposal the Decision Log messages use the alias and the Status messages use the alias AND the resource. Regardless of where we land, is it possible to make these consistent? I think changing the naming to the above would deal with this.

4. No strong opinion about the new format of the bundle structure in the Decision Log messages but another option would be:

```json
{
  "revisions": {
     "authz/bundle.tar.gz": "kjsfkjahfdsasdhfaljfskdf",
     "authz/context": "kjsafhsfaksksksjsdjsksa"
  }
}
```
