### ISSUE TITLE
/bootstrap/authz.rego gives rego_parse_error

### ISSUE THREAD

**Issue by Skoucail** [open-policy-agent/opa#7262]
When updating my Kubernetes OPA deployment from v0 to v1 i got the errors below.

```
error: load error: 4 errors occurred during loading:
/bootstrap/authz.rego:4: rego_parse_error: `if` keyword is required before rule body
/bootstrap/authz.rego:5: rego_parse_error: `if` keyword is required before rule body
/bootstrap/authz.rego:7: rego_parse_error: `if` keyword is required before rule body
/bootstrap/authz.rego:8: rego_parse_error: `if` keyword is required before rule body
```

My deployment is on Kubernetes (k3s).
With the opa-kube-mgmt helm chart version 8.5.12.
The image used for OPA is 1.0.0-envoy-4.

Helm values of my deployment:
```
image:
  tag: 1.0.0-envoy-4
useHttps: false
extraArgs:
  - '--set=plugins.envoy_ext_authz_grpc.addr=0.0.0.0:9191'
  - '--set=plugins.envoy_ext_authz_grpc.query=data.envoy.authz.allow'
  - '--set=decision_logs.console=true'
extraPorts:
  - name: grpc
    appProtocol: grpc
    port: 9191
    protocol: TCP
    targetPort: 9191
mgmt:
  namespaces: "*"
  startupProbe:
    httpGet:
      scheme: HTTP
```

When i change the image back to 0.70.0-envoy-17 everything works without issue.

I can't seem to find the /bootstrap/authz.rego file anywhere on github but i think thats a internal opa file?
