### ISSUE TITLE
Exclude /health endpoint from being traced in distributed tracing

### ISSUE THREAD

**Issue by srenatus** [open-policy-agent/opa#7494]
### Discussed in https://github.com/orgs/open-policy-agent/discussions/686

<div type='discussions-op-text'>

<sup>Originally posted by **loekensgard** April  4, 2025</sup>
Hi,

I am currently configuring distributed tracing for OPA using the following configuration:

```yaml
distributed_tracing:
  type: grpc
  address: <address>
  service_name: <custom_name>
  resource:
    deployment_environment: Dev/Qa/Prod
```
    
I would like to know if there is a way to exclude the /health endpoint from being traced. I am aware that other languages have filters to support this functionality, but I couldn't find any documentation for OPA regarding this. 

Any guidance or suggestions would be greatly appreciated.

Thank you!
</div>

> Additionally, it would be helpful if we could configure it to exclude the /health endpoint from tracing only if the response status is 200. If the /health endpoint returns a 400 status or higher, it should still be logged.
