### ISSUE TITLE
Handle arbitrary webhooks to support integrations

### ISSUE THREAD

**Issue by charlieegan3** [open-policy-agent/opa#7504]
## What is the underlying problem you're trying to solve?

I spoke to some folk at KubeCon last week about an integration with Traefik. I was interested to see if it were possible to integrate with Traefik via webhook natively using [`forwardAuth`](https://doc.traefik.io/traefik/master/middlewares/http/forwardauth).

## Describe the ideal solution

OPA would be able to receive a web request from Traefik and respond with 200OK or a 401 error and optional message if the request is to be denied.

Ideally, OPA would be able to respond to arbitrary HTTP requests and produce an arbitrary response as this would be the most useful to other integrations too. A policy result could be evaluated and contain a response code, headers and optional body to present to the downstream caller.

It'd be a REST endpoint or a mode of an existing endpoint so that decisions are logged. It is also important that all parts of the incoming request are available:

- Method
- Path and params
- Headers
- Body if set

And that the Headers and response body are fully customisable in the policy.

## Describe a "Good Enough" solution

Currently, this is almost possible with some hacks using OPA's native authz functionality.

```
opa run -s -w policy.rego --set decision_logs.console=true --authorization=basic
```

```rego
# policy.rego
package system.authz

# other requests not from traefik are allowed
default allow := true

allow := {
	"allowed": false,
	"reason": "Not allowed",
} if {
	input.path == ["v1", "data", "traefik", "authz"]
	# simple policy example based on header authz
	not input.headers.Authorization == ["foobar"]
}
```

Run traefik:

```
traefik --configFile=traefik.yaml
```

```yaml
# traefik.yaml
log:
  level: DEBUG
api:
  insecure: true
  dashboard: true
entryPoints:
  web:
    address: ":8081"
providers:
  file:
    directory: "config"
```

```yaml
# config/foobar.yaml
http:
  routers:
    my-app-router:
      rule: "PathPrefix(`/`)"
      middlewares:
      - my-forward-auth
      service: my-backend-service
  middlewares:
    my-forward-auth:
      forwardAuth:
        # hack, there is nothing loaded here.
        address: "http://localhost:8181/v1/data/traefik/authz"
  services:
    my-backend-service:
      loadBalancer:
        servers:
        - url: "http://localhost:8000" 
```

This is not ideal because:

- We cannot set the response code.
- We need to enable authz OPA wide and allow all other paths.
- We cannot access the request body if sent. [forwardBody](https://doc.traefik.io/traefik/master/middlewares/http/forwardauth/#forwardbody) doesn't seem to work as expected for me and I have not dug into why it's not being sent.
- We get no decision logs in OPA. ⚠ 

# Additional Context

This has come up before:
- https://github.com/open-policy-agent/opa/issues/3539
- https://github.com/ory/oathkeeper/issues/1125 (another possible integration that might benefit)
- I understand we might be able to integrate with NGINX auth_request via this model too: https://nginx.org/en/docs/http/ngx_http_auth_request_module.html
