### ISSUE TITLE
Refactor compliance tests from YAML to Rego

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/opa#7573]
YAML might have been the best choice at the time, but now that metadata is easily represented in Rego, we should have our compliance tests be Rego files rather than Rego embedded in YAML docs. Working with Rego directly means we can have syntax highlighting, debugging, linting, editor support, and all the other niceties we now have for Rego authoring.

Taking the first test I found as an example, I suggest that instead of this:
```yaml
---
cases:
  - note: aggregates/count
    query: data.generated.p = x
    modules:
      - |
        package generated

        p contains x if {
        	__local0__ = data.a
        	count(__local0__, x)
        }
    data:
      a:
        - 1
        - 2
        - 3
        - 4
    want_result:
      - x:
          - 4
    sort_bindings: true
```

We'd do this:
```rego
# METADATA
# title: aggregates/count
# custom:
#   query: data.generated.p = x
#   data: {a: [1, 2, 3, 4]}
#   want_result: [{x: [4]}]
package generated

p contains x if {
	__local0__ = data.a
	count(__local0__, x)
}
```

Metadata comments are of course just YAML too, so the query/data/input attributes can remain as such, just embedded in the policy, and parsed by the test runner.

I'm sure there are some details we'd have to give some more thought to, but posting this here to start somewhere.
