### ISSUE TITLE
Improve GraphQL Parser Error Handling

### ISSUE THREAD

**Issue by robmyersrobmyers** [open-policy-agent/opa#7622]
## Description

OPA incorrectly assumes that the gqlparser will always include location information in its errors, which is usually, but not always the case.

When this happens it causes a panic with index out of range error.

```
--- FAIL: TestRego (0.48s)
    --- FAIL: TestRego/v1/graphql_is_valid/undefined_argument_schema_ast (0.00s)
panic: runtime error: index out of range [3] with length 2 [recovered]
	panic: runtime error: index out of range [3] with length 2

goroutine 65 [running]:
testing.tRunner.func1.2({0x100f25500, 0x140008a34a0})
	/opt/homebrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1734 +0x1ac
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.24.3/libexec/src/testing/testing.go:1737 +0x334
panic({0x100f25500?, 0x140008a34a0?})
	/opt/homebrew/Cellar/go/1.24.3/libexec/src/runtime/panic.go:792 +0x124
github.com/open-policy-agent/opa/v1/topdown.validateQuery(0x100f813b8?, 0x101533ea0?)
	/opa/v1/topdown/graphql.go:66 +0x180
github.com/open-policy-agent/opa/v1/topdown.builtinGraphQLIsValid({{0x100f813b8, 0x101533ea0}, {0x100f85350, 0x14000402a80}, {0x100f7c8c0, 0x140000421f0}, 0x14000b00480, {0x0, 0x0}, 0x0, ...}, ...)
	/opa/v1/topdown/graphql.go:497 +0x208
```

Tested against `main@4d0820de04`

## Steps To Reproduce

One way to reproduce this is to provide a GraphQL query AST that references a non-existent argument to a mutation in a schema AST.

There may be others.

```yaml
cases:
  - note: graphql_is_valid/undefined argument schema ast
    query: data.test.p = x
    modules:
      - |
        package test

        schema_ast := {
          "Definitions": [
            {
              "BuiltIn": false,
              "Description": "",
              "Fields": [
                {
                  "Description": "",
                  "Name": "bar",
                  "Type": {
                    "NamedType": "String",
                    "NonNull": true
                  }
                }
              ],
              "Kind": "OBJECT",
              "Name": "Query"
            },
            {
              "BuiltIn": false,
              "Description": "",
              "Fields": [
                {
                  "Description": "",
                  "Name": "x",
                  "Type": {
                    "NamedType": "String",
                    "NonNull": true
                  }
                }
              ],
              "Kind": "OBJECT",
              "Name": "Mutation"
            }
          ]
        }

        query_ast := {
          "Operations": [
            {
              "Name": "",
              "Operation": "mutation",
              "SelectionSet": [
                {
                  "Alias": "x",
                  "Arguments": [
                    {
                      "Name": "a",
                      "Value": {
                        "Kind": 7,
                        "Raw": "b"
                      }
                    }
                  ],
                  "Name": "x"
                }
              ]
            }
          ]
        }

        p if {
          graphql.is_valid(query_ast, schema_ast)
        }
    want_result:
      - x: false
```
